/* Music & Beats V17 — hardware workstation UI, richer synth library, FX rack and EDM arp engine. */
const V17_KEY_LIBRARY={
  'Neo Soul EP':{oscs:[['sine',0,.58,-5],['triangle',12,.22,7],['sine',19,.08,-3]],attack:.008,decay:.34,sustain:.52,release:.78,filter:5200,q:.55,gain:.78,v17:{category:'Electric Keys',filterEnv:1.18}},
  'Crystal House':{oscs:[['sine',0,.48,0],['triangle',12,.2,8],['sine',24,.12,-7],['sine',31,.05,4]],attack:.002,decay:.18,sustain:.28,release:.62,filter:9200,q:.7,gain:.72,v17:{category:'House Keys',filterEnv:1.28}},
  'Analog Poly':{oscs:[['sawtooth',0,.36,-9],['sawtooth',0,.34,9],['triangle',-12,.16,0]],attack:.028,decay:.28,sustain:.62,release:.7,filter:3900,q:1.15,gain:.55,v17:{category:'Synth',filterEnv:1.42}},
  'Neon Supersaw':{oscs:[['sawtooth',0,.24,-18],['sawtooth',0,.24,-9],['sawtooth',0,.24,0],['sawtooth',0,.24,9],['sawtooth',0,.24,18],['sine',-12,.08,0]],attack:.012,decay:.2,sustain:.7,release:.54,filter:7600,q:.8,gain:.43,v17:{category:'EDM',filterEnv:1.32}},
  'Future Pluck':{oscs:[['triangle',0,.48,-4],['sawtooth',12,.19,6],['sine',24,.09,-2]],attack:.002,decay:.11,sustain:.07,release:.3,filter:8700,q:1.5,gain:.65,v17:{category:'EDM',filterEnv:1.65}},
  'Festival Lead':{oscs:[['sawtooth',0,.34,-10],['sawtooth',0,.34,10],['square',12,.1,0],['sine',-12,.08,0]],attack:.006,decay:.15,sustain:.72,release:.28,filter:6900,q:1.4,gain:.48,v17:{category:'Lead',filterEnv:1.3}},
  'Vapor Pad':{oscs:[['triangle',0,.32,-11],['sawtooth',12,.17,12],['sine',7,.19,-5],['sine',19,.08,6]],attack:.52,decay:.62,sustain:.72,release:2.3,filter:4300,q:.45,gain:.46,v17:{category:'Pad',filterEnv:1.08}},
  'Trance Organ':{oscs:[['sine',0,.35,0],['sine',12,.25,0],['sine',19,.16,0],['square',24,.06,0]],attack:.008,decay:.05,sustain:.86,release:.16,filter:9800,q:.3,gain:.58,v17:{category:'EDM',filterEnv:1}},
  'Digital Bell':{oscs:[['sine',0,.46,0],['sine',19,.18,0],['sine',28,.12,0],['triangle',36,.05,0]],attack:.001,decay:.42,sustain:.09,release:1.4,filter:12000,q:.25,gain:.64,v17:{category:'Mallet',filterEnv:1}},
  'Lo-Fi Keys':{oscs:[['triangle',0,.47,-4],['sine',12,.18,5],['square',-12,.05,0]],attack:.018,decay:.42,sustain:.46,release:.86,filter:3300,q:.55,gain:.68,v17:{category:'Texture',filterEnv:1.05}}
};
const V17_BASS_LIBRARY={
  'Deep Club Sub':{oscs:[['sine',-12,.72,0],['triangle',0,.13,0]],attack:.003,decay:.16,sustain:.73,release:.2,filter:780,q:.7,gain:.74,v17:{category:'Sub',filterEnv:1.12}},
  'Reese Bass':{oscs:[['sawtooth',-12,.33,-14],['sawtooth',-12,.33,14],['square',0,.08,0]],attack:.008,decay:.2,sustain:.68,release:.3,filter:1650,q:1.35,gain:.56,v17:{category:'EDM Bass',filterEnv:1.35}},
  'Acid Bass':{oscs:[['sawtooth',-12,.45,0],['square',0,.16,5]],attack:.002,decay:.12,sustain:.44,release:.13,filter:1450,q:5.5,gain:.58,v17:{category:'Acid',filterEnv:2.4}},
  'FM House Bass':{oscs:[['sine',-12,.55,0],['sine',7,.15,0],['triangle',12,.09,0],['square',0,.06,0]],attack:.002,decay:.18,sustain:.48,release:.2,filter:2400,q:1.1,gain:.7,v17:{category:'House Bass',filterEnv:1.45}},
  'Pluck Bass':{oscs:[['triangle',-12,.5,0],['sawtooth',0,.17,-5],['sine',12,.06,0]],attack:.001,decay:.09,sustain:.08,release:.16,filter:3100,q:1.7,gain:.67,v17:{category:'Pluck Bass',filterEnv:1.9}},
  'Future Growl':{oscs:[['sawtooth',-12,.29,-11],['square',-12,.26,12],['sawtooth',0,.13,0],['sine',-24,.18,0]],attack:.006,decay:.19,sustain:.64,release:.3,filter:2100,q:2.2,gain:.52,v17:{category:'EDM Bass',filterEnv:1.55}}
};
Object.assign(SOUND_PRESETS,V17_KEY_LIBRARY,V17_BASS_LIBRARY);
Object.keys(V17_BASS_LIBRARY).forEach(name=>{if(!V4_BASS_PRESETS.includes(name))V4_BASS_PRESETS.push(name)});

/* ---------- Shared synth FX rack ---------- */
const V17_FX_BOARDS={
  'Clean Studio':{drive:{on:false,amount:.05},chorus:{on:false,amount:.12},delay:{on:false,amount:.12},reverb:{on:true,amount:.18}},
  'Neon Wide':{drive:{on:false,amount:.08},chorus:{on:true,amount:.46},delay:{on:true,amount:.19},reverb:{on:true,amount:.24}},
  'Festival Stack':{drive:{on:true,amount:.34},chorus:{on:true,amount:.24},delay:{on:true,amount:.31},reverb:{on:true,amount:.2}},
  'Dream Hall':{drive:{on:false,amount:.04},chorus:{on:true,amount:.31},delay:{on:true,amount:.39},reverb:{on:true,amount:.62}},
  'Lo-Fi Tape':{drive:{on:true,amount:.19},chorus:{on:true,amount:.14},delay:{on:true,amount:.16},reverb:{on:true,amount:.13}},
  'Acid Room':{drive:{on:true,amount:.47},chorus:{on:false,amount:.08},delay:{on:true,amount:.18},reverb:{on:true,amount:.1}},
  'Bass Forge':{drive:{on:true,amount:.24},chorus:{on:false,amount:.05},delay:{on:false,amount:.06},reverb:{on:true,amount:.08}}
};
const V17_PLAY_FX={board:'Clean Studio',...v6Clone(V17_FX_BOARDS['Clean Studio'])};
let v17SynthRack=null;
function v17LayerFx(layer){if(!layer.synthFx)layer.synthFx={board:layer.source==='bass'?'Bass Forge':'Clean Studio',...v6Clone(V17_FX_BOARDS[layer.source==='bass'?'Bass Forge':'Clean Studio'])};return layer.synthFx}
function v17FxState(){return currentScreen==='record'&&session.layers?.length&&['chords','bass'].includes(sessionLayer().source)?v17LayerFx(sessionLayer()):V17_PLAY_FX}
function v17DriveCurve(amount=0){const n=1024,c=new Float32Array(n),k=1+amount*55;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=Math.tanh(x*k)/Math.tanh(k)}return c}
function v17EnsureSynthRack(){
  buildAudio();if(v17SynthRack)return v17SynthRack;
  const n={};n.input=ctx.createGain();n.drive=ctx.createWaveShaper();n.drive.oversample='4x';n.tone=ctx.createBiquadFilter();n.tone.type='lowpass';n.comp=ctx.createDynamicsCompressor();n.comp.threshold.value=-12;n.comp.knee.value=10;n.comp.ratio.value=3;n.comp.attack.value=.004;n.comp.release.value=.16;n.dry=ctx.createGain();n.chorus=ctx.createDelay(.06);n.chorus.delayTime.value=.018;n.chorusWet=ctx.createGain();n.lfo=ctx.createOscillator();n.depth=ctx.createGain();n.lfo.frequency.value=.66;n.depth.gain.value=.003;n.lfo.connect(n.depth).connect(n.chorus.delayTime);n.lfo.start();n.delay=ctx.createDelay(1.4);n.feedback=ctx.createGain();n.delayWet=ctx.createGain();n.reverb=ctx.createConvolver();n.reverb.buffer=createImpulse();n.reverbWet=ctx.createGain();
  try{synthBus.disconnect()}catch{}
  synthBus.connect(n.input).connect(n.drive).connect(n.tone).connect(n.comp);n.comp.connect(n.dry).connect(master);n.comp.connect(n.chorus).connect(n.chorusWet).connect(master);n.comp.connect(n.delay);n.delay.connect(n.delayWet).connect(master);n.delay.connect(n.feedback).connect(n.delay);n.comp.connect(n.reverb).connect(n.reverbWet).connect(master);v17SynthRack=n;v17ApplyFx();return n
}
function v17ApplyFx(){if(!ctx)return;const n=v17EnsureSynthRack(),s=v17FxState(),x=v4Expr(),t=ctx.currentTime;n.drive.curve=v17DriveCurve(s.drive.on?s.drive.amount:0);n.tone.frequency.setTargetAtTime(clamp(x.tone||7000,700,14000),t,.02);n.chorusWet.gain.setTargetAtTime(s.chorus.on?s.chorus.amount*.52:0,t,.02);n.depth.gain.setTargetAtTime(.001+s.chorus.amount*.011,t,.02);n.delay.delayTime.setTargetAtTime(.12+s.delay.amount*.52,t,.02);n.feedback.gain.setTargetAtTime(s.delay.on?Math.min(.62,.08+s.delay.amount*.56):0,t,.02);n.delayWet.gain.setTargetAtTime(s.delay.on?s.delay.amount*.48:0,t,.02);const space=clamp(x.space??.18,0,.75);n.reverbWet.gain.setTargetAtTime(s.reverb.on?(space*.36+s.reverb.amount*.34):space*.18,t,.02)}
function v17ApplyBoard(state,name){const p=V17_FX_BOARDS[name];if(!p)return;state.board=name;['drive','chorus','delay','reverb'].forEach(k=>state[k]={...p[k]});if(ctx)v17ApplyFx()}
function v17FxMarkup(state,kind){return `<section class="v17-fx-rack" data-v17-rack><div class="v17-rack-face"><span class="v17-screw a"></span><span class="v17-screw b"></span><div><small>${kind==='bass'?'LOW FREQUENCY PROCESSOR':'SYNTH EFFECTS PROCESSOR'}</small><strong>${kind==='bass'?'M&B BASS FORGE':'M&B PERFORMANCE RACK'}</strong></div><label>BOARD<select data-v17-board>${Object.keys(V17_FX_BOARDS).map(n=>`<option ${n===state.board?'selected':''}>${n}</option>`).join('')}</select></label><i class="v17-power-led"></i></div><div class="v17-pedal-row">${['drive','chorus','delay','reverb'].map(k=>{const s=state[k],label={drive:'SATURATE',chorus:'CHORUS',delay:'ECHO',reverb:'SPACE'}[k];return `<div class="v17-pedal ${s.on?'on':''}" data-v17-pedal="${k}"><span>${label}</span><div class="v17-mini-knob" data-v17-fx-knob data-value="${s.amount}" aria-label="${label} amount"><i></i></div><button type="button" data-v17-stomp aria-label="Toggle ${label}"><i></i></button><small>${s.on?'ACTIVE':'BYPASS'}</small></div>`}).join('')}</div></section>`}
function v17BindFxRack(root,state){if(!root||root.dataset.bound==='1')return;root.dataset.bound='1';root.querySelector('[data-v17-board]')?.addEventListener('change',e=>{v17ApplyBoard(state,e.target.value);v17RefreshFxRack(root,state)});root.querySelectorAll('.v17-pedal').forEach(p=>{const k=p.dataset.v17Pedal;p.querySelector('[data-v17-stomp]')?.addEventListener('click',()=>{state[k].on=!state[k].on;if(ctx)v17ApplyFx();v17RefreshFxRack(root,state)});v17BindValueKnob(p.querySelector('[data-v17-fx-knob]'),0,1,.01,state[k].amount,v=>{state[k].amount=v;if(ctx)v17ApplyFx()})})}
function v17RefreshFxRack(root,state){if(!root?.parentNode)return;const kind=currentScreen==='record'&&sessionLayer()?.source==='bass'||currentScreen==='play'&&playInstrument==='bass'?'bass':'keys';const shell=document.createElement('div');shell.innerHTML=v17FxMarkup(state,kind);const fresh=shell.firstElementChild;root.replaceWith(fresh);v17BindFxRack(fresh,state)}

/* ---------- Richer voice engine (keeps V13 hard-stop semantics) ---------- */
startVoice=function(m,p='Studio Grand',v=.86){
  primeAudio();v17EnsureSynthRack();v17ApplyFx();const s=SOUND_PRESETS[p]||SOUND_PRESETS['Studio Grand'],x=v4Expr(),now=ctx.currentTime,g=ctx.createGain(),f=ctx.createBiquadFilter();f.type='lowpass';const baseCut=Math.min(16000,Math.max(500,x.tone||s.filter));f.frequency.setValueAtTime(Math.min(16000,baseCut*(s.v17?.filterEnv||1)),now);f.frequency.exponentialRampToValueAtTime(Math.max(450,baseCut),now+Math.max(.04,s.decay*.72));f.Q.value=s.q||.3;const velocity=clamp((v||.86)*(x.velocity||.78),.03,1.25),peak=Math.max(.001,s.gain*velocity);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(peak,now+s.attack+.004);g.gain.exponentialRampToValueAtTime(Math.max(.001,peak*s.sustain),now+s.attack+s.decay+.01);f.connect(g).connect(synthBus);const os=s.oscs.map((def,i)=>{const[type,semi,lev,cents=0]=def,o=ctx.createOscillator(),og=ctx.createGain();o.type=type;o.frequency.value=midiToFreq(m+semi);o.detune.value=cents;og.gain.value=lev;o.connect(og).connect(f);o.start(now);return o});let stopped=false;const release=Math.max(.035,(x.sustain||.8)*.68+s.release*.34);const voice={stop(){if(stopped)return;stopped=true;const t=ctx.currentTime;try{g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(Math.max(.0001,g.gain.value),t);g.gain.exponentialRampToValueAtTime(.0001,t+release);os.forEach(o=>o.stop(t+release+.04))}catch{}activeVoices.delete(voice);updateVoiceBadges()},hardStop(){if(stopped)return;stopped=true;const t=ctx.currentTime;try{g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(Math.max(.0001,g.gain.value),t);g.gain.linearRampToValueAtTime(0,t+.006);os.forEach(o=>o.stop(t+.012))}catch{}activeVoices.delete(voice);updateVoiceBadges()}};activeVoices.add(voice);updateVoiceBadges();return voice
};

/* ---------- Hardware knobs ---------- */
function v17SetKnobVisual(knob,min,max,value){const r=(value-min)/(max-min),deg=-135+clamp(r,0,1)*270;knob.style.setProperty('--turn',`${deg}deg`);knob.setAttribute('aria-valuenow',String(Math.round(value*100)/100))}
function v17BindValueKnob(knob,min,max,step,value,onChange){if(!knob||knob.dataset.bound==='1')return;knob.dataset.bound='1';let val=+value;knob.tabIndex=0;knob.setAttribute('role','slider');knob.setAttribute('aria-valuemin',String(min));knob.setAttribute('aria-valuemax',String(max));v17SetKnobVisual(knob,min,max,val);let startY=0,startVal=val;knob.addEventListener('pointerdown',e=>{e.preventDefault();startY=e.clientY;startVal=val;knob.setPointerCapture?.(e.pointerId);knob.classList.add('turning')});knob.addEventListener('pointermove',e=>{if(!knob.hasPointerCapture?.(e.pointerId))return;const units=(startY-e.clientY)/120*(max-min);val=clamp(Math.round((startVal+units)/step)*step,min,max);v17SetKnobVisual(knob,min,max,val);onChange(val)});const end=e=>{try{knob.releasePointerCapture?.(e.pointerId)}catch{}knob.classList.remove('turning')};knob.addEventListener('pointerup',end);knob.addEventListener('pointercancel',end);knob.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].includes(e.key))return;e.preventDefault();val=clamp(val+(['ArrowUp','ArrowRight'].includes(e.key)?step:-step),min,max);v17SetKnobVisual(knob,min,max,val);onChange(val)})}
function v17KnobifyExpression(strip){if(!strip||strip.dataset.v17Knobs==='1')return;strip.dataset.v17Knobs='1';strip.classList.add('v17-knob-strip');strip.querySelectorAll('label').forEach(label=>{const input=label.querySelector('[data-expr]'),title=label.querySelector('span'),out=title?.querySelector('b');if(!input)return;const min=+input.min,max=+input.max,step=+(input.step||1),knob=document.createElement('div');knob.className='v17-hw-knob';knob.innerHTML='<span class="v17-knob-cap"><i></i></span>';input.classList.add('v17-knob-source');label.insertBefore(knob,input);v17BindValueKnob(knob,min,max,step,+input.value,v=>{input.value=String(v);input.dispatchEvent(new Event('input',{bubbles:true}));if(ctx)v17ApplyFx()});label.classList.add('v17-knob-cell');if(title){title.classList.add('v17-knob-label');if(out)out.classList.add('v17-knob-readout')}})}

/* ---------- EDM Arpeggiator ---------- */
const V17_ARP_DEFAULTS={swing:0,pattern:[true,true,true,true,true,true,true,true],ratchet:1,offset:0,motion:'none',distance:12,steps:0,velocityMode:'flat',retrigger:'note'};
Object.entries(V17_ARP_DEFAULTS).forEach(([k,v])=>{if(v6Arp[k]===undefined)v6Arp[k]=Array.isArray(v)?[...v]:v});v6Arp.totalSteps=0;
function v17ArpStateCopy(src=v6Arp){return{enabled:!!src.enabled,mode:src.mode||'up',rate:src.rate||'1/8',octaves:+src.octaves||1,gate:+src.gate||.62,latch:!!src.latch,swing:+src.swing||0,pattern:[...(src.pattern||V17_ARP_DEFAULTS.pattern)],ratchet:+src.ratchet||1,offset:+src.offset||0,motion:src.motion||'none',distance:+src.distance||12,steps:+src.steps||0,velocityMode:src.velocityMode||'flat',retrigger:src.retrigger||'note'}}
const V17_PLAY_ARP=v17ArpStateCopy(v6Arp);
function v17LayerArp(layer,kind){const key=kind==='bass'?'bassArp':'smartArp';if(!layer[key])layer[key]={...v17ArpStateCopy(),enabled:false,pattern:[...V17_ARP_DEFAULTS.pattern]};return layer[key]}
function v17ApplyArpState(s){['enabled','mode','rate','octaves','gate','latch','swing','ratchet','offset','motion','distance','steps','velocityMode','retrigger'].forEach(k=>v6Arp[k]=s[k]);v6Arp.pattern=[...(s.pattern||V17_ARP_DEFAULTS.pattern)]}
function v17CaptureArpState(s){Object.assign(s,v17ArpStateCopy(v6Arp));s.pattern=[...v6Arp.pattern]}
function v17ArpVelocity(step){const mode=v6Arp.velocityMode||'flat',p=step%8;if(mode==='accent')return p%4===0?.94:p%2===0?.76:.62;if(mode==='rampup')return .54+(p/7)*.38;if(mode==='rampdown')return .92-(p/7)*.36;if(mode==='pulse')return p%2===0?.9:.58;return .76}
function v17MotionSemis(step,seqLen){const count=Math.max(0,+v6Arp.steps||0);if(!count)return 0;const cycle=Math.floor(step/Math.max(1,seqLen)),span=count+1;let n=cycle%span;if(v6Arp.motion==='down')n=-n;else if(v6Arp.motion==='pendulum'){const period=Math.max(1,count*2),x=cycle%period;n=x<=count?x:period-x}else if(v6Arp.motion!=='up')n=0;return n*(+v6Arp.distance||12)}
const v17BaseArpSequence=v6ArpSequence;
v6ArpSequence=function(target){let seq=v17BaseArpSequence(target);if(v6Arp.mode==='downup'&&seq.length>2)seq=[...seq.slice().reverse(),...seq.slice(1,-1)];return seq};
function v17ArpStepNotes(target,seq,idx,transpose){if(v6Arp.mode==='chord'&&target?.chord)return v6ChordNotes(target.chord,target.voicing||'close',target.octave).map(m=>m+transpose);const off=(idx+(+v6Arp.offset||0))%seq.length,m=v6Arp.mode==='random'?seq[Math.floor(Math.random()*seq.length)]:seq[off];return[m+transpose]}
v6ArpTick=function(){
  if(!v6Arp.enabled||!v6Arp.target)return;const target=v6Arp.target,seq=v6ArpSequence(target);if(!seq.length)return;const stepMs=v6RateMs(),stepNo=v6Arp.totalSteps||0,mask=v6Arp.pattern||V17_ARP_DEFAULTS.pattern,playStep=mask[stepNo%mask.length]!==false,transpose=v17MotionSemis(stepNo,seq.length),notes=v17ArpStepNotes(target,seq,v6Arp.index%seq.length,transpose),ratchet=clamp(+v6Arp.ratchet||1,1,4),sub=stepMs/ratchet,vel=v17ArpVelocity(stepNo);
  if(playStep){for(let r=0;r<ratchet;r++)setTimeout(()=>{if(!v6Arp.enabled||v6Arp.target!==target)return;notes.forEach((m,j)=>{const voice=startVoice(m,target.preset,clamp(vel-j*.025,.35,1));v6Arp.voices.push(voice);setTimeout(()=>{voice.stop();v6Arp.voices=v6Arp.voices.filter(v=>v!==voice)},Math.max(30,sub*clamp(+v6Arp.gate||.62,.08,1.5)))})},r*sub)}
  v6PaintArp(stepNo);v6Arp.index++;v6Arp.totalSteps=stepNo+1;if(v6Arp.retrigger==='beat'&&v6Arp.totalSteps%16===0)v6Arp.index=0;const swing=clamp(+v6Arp.swing||0,0,70)/100*.58,interval=stepMs*(stepNo%2===0?1+swing:1-swing);v6Arp.nextAt+=interval;v6Arp.timer=setTimeout(v6ArpTick,Math.max(5,v6Arp.nextAt-performance.now()))
};
v6StartArp=function(target){
  if(typeof v7ArpReleaseTimer!=='undefined'){clearTimeout(v7ArpReleaseTimer);v7ArpReleaseTimer=null}if(!v6Arp.enabled)return;const previous=v6Arp.target;previous?.pad?.classList.remove('arp-active');v6Arp.target=target;target.pad?.classList.add('arp-active');if(!v6Arp.timer){v6Arp.index=0;v6Arp.totalSteps=0;v6Arp.nextAt=performance.now()+8;v6Arp.timer=setTimeout(v6ArpTick,8)}else if(v6Arp.retrigger==='note'&&(previous?.chord!==target.chord||previous?.rootMidi!==target.rootMidi)){v6Arp.index=0;v6Arp.totalSteps=0}
};
function v17ArpAdvancedMarkup(state){return `<details class="v17-arp-advanced"><summary><span>EDM MOTION</span><small>Swing · pattern · ratchet · transpose · velocity</small></summary><div class="v17-arp-advanced-grid"><label>Swing<input data-v17-arp="swing" type="range" min="0" max="70" value="${state.swing}"></label><label>Ratchet<select data-v17-arp="ratchet"><option>1</option><option ${+state.ratchet===2?'selected':''}>2</option><option ${+state.ratchet===3?'selected':''}>3</option><option ${+state.ratchet===4?'selected':''}>4</option></select></label><label>Offset<select data-v17-arp="offset">${Array.from({length:8},(_,i)=>`<option ${+state.offset===i?'selected':''}>${i}</option>`).join('')}</select></label><label>Motion<select data-v17-arp="motion"><option value="none">Static</option><option value="up" ${state.motion==='up'?'selected':''}>Climb</option><option value="down" ${state.motion==='down'?'selected':''}>Dive</option><option value="pendulum" ${state.motion==='pendulum'?'selected':''}>Pendulum</option></select></label><label>Steps<select data-v17-arp="steps">${[0,1,2,3,4].map(v=>`<option ${+state.steps===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Distance<select data-v17-arp="distance">${[2,5,7,12].map(v=>`<option ${+state.distance===v?'selected':''} value="${v}">${v===12?'Octave':v+' st'}</option>`).join('')}</select></label><label>Velocity<select data-v17-arp="velocityMode"><option value="flat">Flat</option><option value="accent" ${state.velocityMode==='accent'?'selected':''}>Accent</option><option value="pulse" ${state.velocityMode==='pulse'?'selected':''}>Pulse</option><option value="rampup" ${state.velocityMode==='rampup'?'selected':''}>Ramp ↑</option><option value="rampdown" ${state.velocityMode==='rampdown'?'selected':''}>Ramp ↓</option></select></label><label>Retrigger<select data-v17-arp="retrigger"><option value="note">New note</option><option value="beat" ${state.retrigger==='beat'?'selected':''}>Every bar</option><option value="free" ${state.retrigger==='free'?'selected':''}>Free run</option></select></label><div class="v17-pattern"><span>RHYTHM</span>${(state.pattern||V17_ARP_DEFAULTS.pattern).map((on,i)=>`<button type="button" data-v17-step="${i}" class="${on?'on':''}"><i></i></button>`).join('')}</div></div></details>`}
function v17BindArpAdvanced(root,state){if(!root)return;root.querySelectorAll('[data-v17-arp]').forEach(el=>{const apply=()=>{const k=el.dataset.v17Arp,v=['swing','ratchet','offset','steps','distance'].includes(k)?+el.value:el.value;state[k]=v;v17ApplyArpState(state)};el.addEventListener('input',apply);el.addEventListener('change',apply)});root.querySelectorAll('[data-v17-step]').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.v17Step;state.pattern[i]=!state.pattern[i];b.classList.toggle('on',state.pattern[i]);v17ApplyArpState(state)}))}
function v17UpgradePlayArp(){const p=$('#v6ArpPanel');if(!p||p.dataset.v17==='1')return;p.dataset.v17='1';p.classList.add('v17-hardware-arp');const mode=p.querySelector('[data-arp="mode"]');if(mode){mode.innerHTML='<option value="up">Up</option><option value="down">Down</option><option value="updown">Up / Down</option><option value="downup">Down / Up</option><option value="random">Random</option><option value="chord">Chord Pulse</option>';mode.value=V17_PLAY_ARP.mode;mode.addEventListener('input',()=>{V17_PLAY_ARP.mode=mode.value})}const rate=p.querySelector('[data-arp="rate"]');if(rate&&!rate.querySelector('option[value="1/32"]'))rate.insertAdjacentHTML('beforeend','<option value="1/32">1/32</option>');const gate=p.querySelector('[data-arp="gate"]');if(gate){gate.max='1.5';gate.step='.01'}const controls=p.querySelector('.v6-arp-controls');controls?.insertAdjacentHTML('beforeend',v17ArpAdvancedMarkup(V17_PLAY_ARP));v17BindArpAdvanced(p,V17_PLAY_ARP);p.querySelectorAll('[data-arp]').forEach(el=>el.addEventListener('input',()=>{setTimeout(()=>{v17CaptureArpState(V17_PLAY_ARP)},0)}));const power=p.querySelector('.v6-arp-power');if(power){power.classList.add('v17-rocker');const span=power.querySelector('span');if(span)span.textContent='ARP'}v6SyncArpUI=function(){const panel=$('#v6ArpPanel');if(!panel)return;const power=panel.querySelector('.v6-arp-power');power?.classList.toggle('active',v6Arp.enabled);if(power?.querySelector('span'))power.querySelector('span').textContent='ARP';const latch=panel.querySelector('[data-arp-toggle="latch"]');if(latch){latch.classList.toggle('active',v6Arp.latch);latch.textContent=v6Arp.latch?'LATCHED':'LATCH'}}}

/* ---------- Compact full-feature arp modules in Record ---------- */
function v17CompactArpMarkup(kind,state){const name=kind==='bass'?'BASS ARP':'SMART KEYS ARP';return `<section class="v17-record-arp ${state.enabled?'active':''}" data-v17-record-arp="${kind}"><div class="v17-record-arp-head"><div><small>PATTERN MODULE</small><strong>${name}</strong></div><button class="v17-arp-rocker ${state.enabled?'active':''}" data-v17-power type="button"><i></i><span>ARP</span></button></div><div class="v17-record-arp-main"><label>Direction<select data-basic="mode"><option value="up">Up</option><option value="down">Down</option><option value="updown">Up / Down</option><option value="downup">Down / Up</option><option value="random">Random</option><option value="chord">Chord Pulse</option></select></label><label>Rate<select data-basic="rate"><option>1/4</option><option>1/8</option><option>1/16</option><option value="1/8T">1/8 Triplet</option><option>1/32</option></select></label><label>Range<select data-basic="octaves"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>Gate<input data-basic="gate" type="range" min=".08" max="1.5" step=".01" value="${state.gate}"></label><button class="v17-stomp-small ${state.latch?'active':''}" data-v17-latch type="button"><i></i><span>LATCH</span></button><button class="v17-stop-small" data-v17-stop type="button">STOP</button></div>${v17ArpAdvancedMarkup(state)}</section>`}
function v17BindRecordArp(panel,layer,kind){if(!panel||panel.dataset.bound==='1')return;panel.dataset.bound='1';const state=v17LayerArp(layer,kind),sync=()=>{panel.classList.toggle('active',state.enabled);panel.querySelector('[data-v17-power]')?.classList.toggle('active',state.enabled);panel.querySelector('[data-v17-latch]')?.classList.toggle('active',state.latch)};panel.querySelector('[data-v17-power]').onclick=()=>{state.enabled=!state.enabled;if(!state.enabled)v15HardStopArp();v17ApplyArpState(state);sync()};panel.querySelector('[data-v17-latch]').onclick=()=>{state.latch=!state.latch;v17ApplyArpState(state);sync()};panel.querySelector('[data-v17-stop]').onclick=()=>v15HardStopArp();panel.querySelectorAll('[data-basic]').forEach(el=>{const k=el.dataset.basic;el.value=String(state[k]);const apply=()=>{state[k]=['octaves','gate'].includes(k)?+el.value:el.value;v17ApplyArpState(state)};el.addEventListener('input',apply);el.addEventListener('change',apply)});v17BindArpAdvanced(panel,state);sync()}
const v17SmartPointers=new Map();
function v17RecordSmartEnabled(){return currentScreen==='record'&&session.layers?.length&&sessionLayer().source==='chords'&&v17LayerArp(sessionLayer(),'smart').enabled}
function v17SmartTarget(pad){const c=v14PadContext(pad);if(!c)return null;return{chord:c.chord,pad,preset:c.preset,octave:c.octave,voicing:c.voicing,context:'record',bpm:session.bpm}}
function v17BindRecordSmartPads(host){if(!host||host.dataset.v17Arp==='1')return;host.dataset.v17Arp='1';host.addEventListener('pointerdown',e=>{if(!v17RecordSmartEnabled())return;const pad=e.target.closest('.chord-pad');if(!pad||!host.contains(pad))return;e.preventDefault();e.stopImmediatePropagation();v17ApplyArpState(v17LayerArp(sessionLayer(),'smart'));const target=v17SmartTarget(pad);if(!target)return;v6StartArp(target);v17SmartPointers.set(e.pointerId,{host,pad});try{host.setPointerCapture(e.pointerId)}catch{}},true);host.addEventListener('pointermove',e=>{const hit=v17SmartPointers.get(e.pointerId);if(!hit||hit.host!==host||!v17RecordSmartEnabled())return;const pad=document.elementFromPoint(e.clientX,e.clientY)?.closest('.chord-pad');if(!pad||!host.contains(pad)||pad===hit.pad)return;hit.pad.classList.remove('arp-active');const target=v17SmartTarget(pad);if(target)v6StartArp(target);hit.pad=pad},true);const end=e=>{const hit=v17SmartPointers.get(e.pointerId);if(!hit||hit.host!==host)return;e.preventDefault();e.stopImmediatePropagation();v17SmartPointers.delete(e.pointerId);hit.pad.classList.remove('arp-active');if(!v6Arp.latch)v6StopArp(true)};host.addEventListener('pointerup',end,true);host.addEventListener('pointercancel',end,true);host.addEventListener('lostpointercapture',end,true)}
const v17BaseLatchPad=typeof v14LatchPad==='function'?v14LatchPad:null;
if(v17BaseLatchPad)v14LatchPad=function(pad){const c=v14PadContext(pad);if(!c||c.id!=='#recordChords'||!v17RecordSmartEnabled())return v17BaseLatchPad(pad);if(v14Latch&&v14Latch.id===c.id&&v14Latch.index===c.index){v14ReleaseLatch(false);return true}v14ReleaseLatch(false);v17ApplyArpState(v17LayerArp(sessionLayer(),'smart'));v6Arp.latch=true;v17LayerArp(sessionLayer(),'smart').latch=true;v6StartArp({chord:c.chord,pad:c.pad,preset:c.preset,octave:c.octave,voicing:c.voicing,context:'record',bpm:session.bpm});v14Latch={...c,arp:true,voices:[]};c.pad.classList.add('v14-latched');c.pad.setAttribute('aria-pressed','true');v14PaintHints();return true};
const v17BaseNumberTrigger=v5TriggerNumberChord,v17BaseNumberRelease=v5ReleaseNumberChord;
v5TriggerNumberChord=function(index){if(!v17RecordSmartEnabled())return v17BaseNumberTrigger(index);if(v5NumberChordVoices.has(index))return true;const c=v5CurrentChordContext(),pad=c?.host?.querySelectorAll('.chord-pad')?.[index];if(!c||!pad)return false;const now=performance.now(),key=`${c.host.id}:${index}`,prev=v14LastNumberTap;if(prev&&prev.key===key&&now-prev.time<=V14_DOUBLE_MS){v14LastNumberTap=null;return v14LatchPad(pad)}v14LastNumberTap={key,time:now};if(v14Latch&&v14Latch.id==='#'+c.host.id&&v14Latch.index===index)return true;v17ApplyArpState(v17LayerArp(sessionLayer(),'smart'));const target=v17SmartTarget(pad);v6StartArp(target);pad.classList.add('keyboard-active');v5NumberChordVoices.set(index,{arp:true,v17RecordArp:true,pad,target});return true};
v5ReleaseNumberChord=function(index){const hit=v5NumberChordVoices.get(index);if(!hit?.v17RecordArp)return v17BaseNumberRelease(index);v5NumberChordVoices.delete(index);hit.pad?.classList.remove('keyboard-active','active');if(!v6Arp.latch&&!([...v5NumberChordVoices.values()].some(x=>x.v17RecordArp)))v6StopArp(true)};

function v17EnhanceRecordArp(){if(currentScreen!=='record'||!session.layers?.length)return;const l=sessionLayer(),kind=l.source==='chords'?'smart':l.source==='bass'?'bass':null;if(!kind)return;const host=kind==='smart'?$('#recordChords'):$('#recordKeyboard'),box=$('#layerSourceTools .tool-box');if(!host||!box)return;let panel=box.querySelector(`[data-v17-record-arp="${kind}"]`);if(!panel){host.insertAdjacentHTML('beforebegin',v17CompactArpMarkup(kind,v17LayerArp(l,kind)));panel=box.querySelector(`[data-v17-record-arp="${kind}"]`)}v17BindRecordArp(panel,l,kind);v17ApplyArpState(v17LayerArp(l,kind));if(kind==='smart')v17BindRecordSmartPads($('#recordChords'));else v15BindBassKeyboard($('#recordKeyboard'),'record')}

/* ---------- Hardware presentation + racks ---------- */
function v17RefreshSoundMenus(){v5NormalizeSoundMenus?.();const play=$('#playBassSound');if(play){const cur=V4_BASS_PRESETS.includes(play.value)?play.value:'Finger Bass';play.innerHTML=V4_BASS_PRESETS.map(n=>`<option ${n===cur?'selected':''}>${n}</option>`).join('');play.value=cur}}
function v17InstallFxRack(){const play=currentScreen==='play',source=play?playInstrument:(session.layers?.length?sessionLayer().source:null);if(!['chords','bass'].includes(source))return;const host=play?$('#playScreen .instrument-panel'):$('#layerSourceTools .tool-box');if(!host)return;let rack=host.querySelector('[data-v17-rack]');const state=play?V17_PLAY_FX:v17LayerFx(sessionLayer()),kind=source==='bass'?'bass':'keys';if(!rack){const anchor=play?host.querySelector('.keyboard-frame'):host.querySelector('.expression-strip')?.closest('.v9-expression-shell')||host.querySelector('.expression-strip')||host.querySelector('.keyboard');if(anchor)anchor.insertAdjacentHTML('beforebegin',v17FxMarkup(state,kind));else host.insertAdjacentHTML('beforeend',v17FxMarkup(state,kind));rack=host.querySelector('[data-v17-rack]')}v17BindFxRack(rack,state);if(ctx)v17ApplyFx()}
function v17Hardwareize(){document.documentElement.classList.add('v17-hardware-ui');document.querySelectorAll('.expression-strip').forEach(v17KnobifyExpression);v17UpgradePlayArp();v17InstallFxRack();v17EnhanceRecordArp();v17RefreshSoundMenus();$('#playInstrumentSkin')?.classList.add('v17-device-face');document.querySelectorAll('.record-instrument-skin,.v6-guitar-hero,.v6-guitar-rig').forEach(e=>e.classList.add('v17-device-face'))}
const v17BaseRenderPlayInstrument=renderPlayInstrument;renderPlayInstrument=function(){if(currentScreen==='play')v17ApplyArpState(V17_PLAY_ARP);const out=v17BaseRenderPlayInstrument.apply(this,arguments);requestAnimationFrame(v17Hardwareize);return out};
const v17BaseRenderLayerTools=renderLayerTools;renderLayerTools=function(){const out=v17BaseRenderLayerTools.apply(this,arguments);requestAnimationFrame(v17Hardwareize);return out};
document.addEventListener('input',e=>{if(e.target?.matches?.('[data-expr]')&&ctx)v17ApplyFx()});
if(typeof v7ProjectPayload==='function'){const v17BaseProjectPayload=v7ProjectPayload;v7ProjectPayload=function(name,id){const p=v17BaseProjectPayload(name,id);p.v17PlayFx=v6Clone(V17_PLAY_FX);p.v17PlayArp=v17ArpStateCopy(V17_PLAY_ARP);p.session.layers.forEach((saved,i)=>{const live=session.layers[i];if(live?.synthFx)saved.synthFx=v6Clone(live.synthFx);if(live?.smartArp)saved.smartArp=v17ArpStateCopy(live.smartArp);if(live?.bassArp)saved.bassArp=v17ArpStateCopy(live.bassArp)});return p}}
function v17Init(){v17RefreshSoundMenus();requestAnimationFrame(v17Hardwareize)}
v17Init();