/* Music & Beats V35 core: presets, settings and project snapshots. */
(()=>{
if(window.MB_V35)return;
const api=window.MB_V34_LOOPER;if(!api)return;const state=api.state,tracks=api.tracks;
const SETTINGS_KEY='musicandbeats:v35:settings',PROJECTS_KEY='musicandbeats:v35:projects',AUTOSAVE_KEY='musicandbeats:v35:autosave';
const ARP_PRESETS={Off:{},'Slow Up':{rateSteps:2,gate:.82,order:[0,1,2,3]},'Up / Down':{rateSteps:1,gate:.68,order:[0,1,2,3,2,1]},Pulse:{rateSteps:1,gate:.5,order:[0,2,1,2,3,2]},Ratchet:{rateSteps:.5,gate:.42,order:[0,1,2,1,3,2]},'Indian Cycle':{rateSteps:1,gate:.78,order:[0,2,1,2,3,2,1,0]}};
const STYLE_PRESETS={Clean:{keys:'Studio Grand',bass:'Sub Bass',beat:'Pop',energy:2,arp:'Off'},Worship:{keys:'Soft Grand',bass:'Sub Bass',beat:'Worship',energy:3,arp:'Slow Up'},Ambient:{keys:'Dream Pad',bass:'Warm Analog',beat:'Lo-Fi',energy:2,arp:'Up / Down'},Pulse:{keys:'Velvet EP',bass:'Sub Bass',beat:'House',energy:4,arp:'Pulse'},Indian:{keys:'Harmonium',bass:'Sub Bass',beat:'Keherwa',energy:3,arp:'Indian Cycle'},Cinematic:{keys:'Air Choir',bass:'Warm Analog',beat:'Rock',energy:2,arp:'Slow Up'}};
const extra={metronome:true,arpPreset:'Off',stylePreset:'Clean',currentProjectId:null,currentProjectName:'',lastAbs:0,wasRunning:false,liveArps:new Map()};
try{Object.assign(extra,JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'))}catch{};if(!ARP_PRESETS[extra.arpPreset])extra.arpPreset='Off';if(!STYLE_PRESETS[extra.stylePreset])extra.stylePreset='Clean';extra.liveArps=new Map();extra.lastAbs=0;extra.wasRunning=false;
const clone=v=>JSON.parse(JSON.stringify(v)),totalSteps=()=>Math.max(16,(+state.bars||4)*16),stepSeconds=()=>60/(+state.bpm||100)/4,wrapStep=v=>((v%totalSteps())+totalSteps())%totalSteps(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persistCore(){try{localStorage.setItem('musicandbeats:v34:looper',JSON.stringify({bpm:state.bpm,bars:state.bars,beatStyle:state.beatStyle,energy:state.energy,beatPattern:state.beatPattern,beats:{muted:!!tracks.beats.muted},keys:{muted:!!tracks.keys.muted,events:tracks.keys.events,sound:tracks.keys.sound,key:tracks.keys.key},bass:{muted:!!tracks.bass.muted,events:tracks.bass.events,sound:tracks.bass.sound,key:tracks.bass.key}}))}catch{}}
function snapshot(){return{version:'v35',name:extra.currentProjectName||'Untitled Jam',savedAt:new Date().toISOString(),looper:{bpm:state.bpm,bars:state.bars,beatStyle:state.beatStyle,energy:state.energy,beatPattern:clone(state.beatPattern),activeLane:state.activeLane,beats:{muted:!!tracks.beats.muted},keys:{muted:!!tracks.keys.muted,events:clone(tracks.keys.events),sound:tracks.keys.sound,key:tracks.keys.key},bass:{muted:!!tracks.bass.muted,events:clone(tracks.bass.events),sound:tracks.bass.sound,key:tracks.bass.key}},extras:{metronome:!!extra.metronome,arpPreset:extra.arpPreset,stylePreset:extra.stylePreset}}}
function autosave(){try{localStorage.setItem(AUTOSAVE_KEY,JSON.stringify(snapshot()))}catch{}}
function persist(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({metronome:!!extra.metronome,arpPreset:extra.arpPreset,stylePreset:extra.stylePreset,currentProjectId:extra.currentProjectId,currentProjectName:extra.currentProjectName}))}catch{};persistCore();autosave();window.dispatchEvent(new CustomEvent('musicandbeats:v35change'))}
function projectList(){try{const x=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function putProjects(x){try{localStorage.setItem(PROJECTS_KEY,JSON.stringify(x))}catch{}}
function saveProject(name=null,forceNew=false){const p=projectList(),now=new Date().toISOString(),finalName=(name||extra.currentProjectName||`Jam ${new Date().toLocaleDateString([], {month:'short',day:'numeric'})}`).trim()||'Untitled Jam';let item=!forceNew&&extra.currentProjectId?p.find(x=>x.id===extra.currentProjectId):null;if(!item){item={id:`p-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,createdAt:now};p.unshift(item)}extra.currentProjectId=item.id;extra.currentProjectName=finalName;Object.assign(item,{name:finalName,updatedAt:now,data:snapshot()});item.data.name=finalName;putProjects(p);persist();return item}
function applySnapshot(snap){if(!snap?.looper)return false;if(state.running)api.stop();const x=snap.looper;state.bpm=Math.max(40,Math.min(220,+x.bpm||100));state.bars=[1,2,4,8].includes(+x.bars)?+x.bars:4;state.beatStyle=BEAT_PRESETS[x.beatStyle]?x.beatStyle:'Worship';state.energy=Math.max(1,Math.min(5,+x.energy||3));state.beatPattern=x.beatPattern?.kick?.length===16?clone(x.beatPattern):loadBeat(state.beatStyle,state.energy,false);state.activeLane=['beats','keys','bass'].includes(x.activeLane)?x.activeLane:'beats';tracks.beats.muted=!!x.beats?.muted;['keys','bass'].forEach(k=>{const y=x[k]||{};tracks[k].muted=!!y.muted;tracks[k].events=Array.isArray(y.events)?clone(y.events):[];if(y.sound&&SOUND_PRESETS[y.sound])tracks[k].sound=y.sound;if(y.key&&NOTES.includes(y.key))tracks[k].key=y.key});if(snap.extras){extra.metronome=snap.extras.metronome!==false;if(ARP_PRESETS[snap.extras.arpPreset])extra.arpPreset=snap.extras.arpPreset;if(STYLE_PRESETS[snap.extras.stylePreset])extra.stylePreset=snap.extras.stylePreset}persist();api.open();return true}
function loadProject(id){const item=projectList().find(x=>x.id===id);if(!item)return false;extra.currentProjectId=item.id;extra.currentProjectName=item.name;return applySnapshot(item.data)}
function deleteProject(id){putProjects(projectList().filter(x=>x.id!==id));if(extra.currentProjectId===id){extra.currentProjectId=null;extra.currentProjectName='';persist()}}
function newProject(){if(state.running)api.stop();tracks.keys.events=[];tracks.bass.events=[];tracks.beats.muted=tracks.keys.muted=tracks.bass.muted=false;state.bpm=100;state.bars=4;state.beatStyle='Worship';state.energy=3;state.beatPattern=loadBeat('Worship',3,false);tracks.keys.sound='Harmonium';tracks.keys.key='C';tracks.bass.sound='Sub Bass';tracks.bass.key='C';extra.currentProjectId=null;extra.currentProjectName='';extra.arpPreset='Off';extra.stylePreset='Clean';extra.metronome=true;persist();api.open()}
function applyStyle(name,refresh=true){const s=STYLE_PRESETS[name];if(!s)return;extra.stylePreset=name;if(SOUND_PRESETS[s.keys])tracks.keys.sound=s.keys;if(SOUND_PRESETS[s.bass])tracks.bass.sound=s.bass;if(BEAT_PRESETS[s.beat]){state.beatStyle=s.beat;state.energy=s.energy;state.beatPattern=loadBeat(s.beat,s.energy,false)}extra.arpPreset=s.arp;persist();if(refresh)api.open()}
window.MB_V35={version:'v35',api,state,tracks,extra,ARP_PRESETS,STYLE_PRESETS,clone,totalSteps,stepSeconds,wrapStep,esc,persist,persistCore,autosave,snapshot,projectList,saveProject,loadProject,deleteProject,newProject,applySnapshot,applyStyle};
})();