/* Music & Beats V36 UI: quick setup, metronome, styles and one project library. */
(()=>{
const V=window.MB_V35;if(!V||V.uiReady)return;V.uiReady=true;const {api,state,extra,STYLE_PRESETS,esc}=V;
let projectButton=null;
function findProjectButtons(){return[...document.querySelectorAll('.top-actions button')].filter(b=>/\bprojects?\b/i.test((b.textContent||'').trim()))}
function bindProjectButton(){const actions=document.querySelector('.top-actions');if(!actions)return;let buttons=findProjectButtons();let preferred=buttons.find(b=>b.id!=='v35ProjectsBtn')||buttons[0];if(!preferred){preferred=document.createElement('button');preferred.className='ghost-btn';preferred.type='button';preferred.innerHTML='<span>▤</span> Projects';actions.insertBefore(preferred,actions.firstChild)}buttons=findProjectButtons();buttons.forEach(b=>{if(b!==preferred)b.remove()});if(!preferred.dataset.v36Bound){const clean=preferred.cloneNode(true);preferred.replaceWith(clean);preferred=clean;preferred.dataset.v36Bound='1'}projectButton=preferred;projectButton.onclick=()=>openProjects(false);projectButton.setAttribute('aria-label','Open projects')}
function syncButtons(){if(projectButton){const label=extra.currentProjectName?`Projects · ${extra.currentProjectName}`:'Projects';const text=[...projectButton.childNodes].find(n=>n.nodeType===Node.TEXT_NODE&&/Projects/i.test(n.textContent||''));if(text)text.textContent=` ${label}`;else if(!projectButton.querySelector('span,svg,i'))projectButton.textContent=label;projectButton.title=label}document.querySelectorAll('#v35MetroToggle,#v35HomeMetro').forEach(b=>{b.classList.toggle('on',extra.metronome);b.setAttribute('aria-pressed',String(extra.metronome));if(b.id==='v35MetroToggle'){const html=`<span>♩</span><strong>Click ${extra.metronome?'On':'Off'}</strong>`;if(b.innerHTML!==html)b.innerHTML=html}else{const t=b.querySelector('b');if(t)t.textContent=extra.metronome?'On':'Off'}});const s=document.querySelector('#v35StyleTop');if(s)s.value=extra.stylePreset}
function installTopbar(){const old=document.querySelector('#saveBtn');if(old&&!old.dataset.v35){const b=old.cloneNode(true);old.replaceWith(b);b.dataset.v35='1';b.hidden=false;b.textContent='Save';b.onclick=()=>extra.currentProjectId?(V.saveProject(),syncButtons()):openProjects(true)}document.querySelector('#v35ProjectsBtn')?.remove();bindProjectButton();syncButtons()}
function installDialog(){document.querySelector('#v7ProjectsDialog')?.remove();if(document.querySelector('#v35ProjectsDialog'))return;const d=document.createElement('dialog');d.id='v35ProjectsDialog';d.className='v35-dialog';d.innerHTML=`<div class="v35-dialog-shell"><header><div><span>PROJECTS</span><h2>Your backing tracks</h2><p>Saved jams reopen directly in the current Beats / Keys / Bass looper.</p></div><button data-close type="button">×</button></header><div class="v35-save-row"><input id="v35ProjectName" maxlength="60" placeholder="Project name"><button id="v35SaveProject" type="button">Save project</button><button id="v35SaveCopy" type="button">Save copy</button></div><div class="v35-dialog-actions"><button id="v35NewProject" type="button">＋ New project</button></div><div id="v35ProjectList" class="v35-project-list"></div></div>`;document.body.appendChild(d);d.querySelector('[data-close]').onclick=closeProjects;d.onclick=e=>{if(e.target===d)closeProjects()};d.querySelector('#v35SaveProject').onclick=()=>{V.saveProject(d.querySelector('#v35ProjectName').value,false);renderProjects();syncButtons()};d.querySelector('#v35SaveCopy').onclick=()=>{extra.currentProjectId=null;V.saveProject(d.querySelector('#v35ProjectName').value,true);renderProjects();syncButtons()};d.querySelector('#v35NewProject').onclick=()=>{V.newProject();closeProjects();V.decorate?.();syncButtons()}}
function openProjects(focus=false){installDialog();document.querySelector('#v7ProjectsDialog')?.remove();const d=document.querySelector('#v35ProjectsDialog');d.querySelector('#v35ProjectName').value=extra.currentProjectName||'';renderProjects();if(!d.open)d.showModal();if(focus)setTimeout(()=>d.querySelector('#v35ProjectName').focus(),30)}
function closeProjects(){const d=document.querySelector('#v35ProjectsDialog');if(d?.open)d.close()}
function renderProjects(){const h=document.querySelector('#v35ProjectList');if(!h)return;const p=V.projectList();h.innerHTML=p.length?p.map(x=>`<article class="${x.id===extra.currentProjectId?'active':''}"><button class="v35-load-project" data-load="${x.id}" type="button"><strong>${esc(x.name)}</strong><small>${new Date(x.updatedAt||x.createdAt).toLocaleString()}</small></button><button class="v35-delete-project" data-delete="${x.id}" type="button">Delete</button></article>`).join(''):'<p class="v35-empty">No saved projects yet. Save this jam and it will appear here.</p>';h.onclick=e=>{const l=e.target.closest('[data-load]'),d=e.target.closest('[data-delete]');if(l){window.MB_V36?.releaseAll?.();V.loadProject(l.dataset.load);closeProjects();V.decorate?.();syncButtons()}if(d&&confirm('Delete this saved project?')){V.deleteProject(d.dataset.delete);renderProjects();syncButtons()}}}
function installHome(){const home=document.querySelector('.v34-home-card');if(!home||home.querySelector('.v35-quick-setup'))return;const enter=document.querySelector('#v34Enter');if(!enter)return;const box=document.createElement('section');box.className='v35-quick-setup';box.innerHTML=`<div class="v35-quick-title"><strong>Quick setup</strong><span>Set the grid before you start.</span></div><div class="v35-quick-grid"><label>BPM<input id="v35HomeBpm" type="number" min="40" max="220" inputmode="numeric" value="${state.bpm}"></label><label>Bars<select id="v35HomeBars">${[1,2,4,8].map(n=>`<option value="${n}" ${n===state.bars?'selected':''}>${n} bar${n===1?'':'s'}</option>`).join('')}</select></label><label>Sound style<select id="v35HomeStyle">${Object.keys(STYLE_PRESETS).map(x=>`<option ${x===extra.stylePreset?'selected':''}>${x}</option>`).join('')}</select></label><label class="v35-toggle-label">Metronome<button id="v35HomeMetro" class="v35-toggle ${extra.metronome?'on':''}" type="button"><span></span><b>${extra.metronome?'On':'Off'}</b></button></label></div>`;enter.before(box);const b=enter.cloneNode(true);enter.replaceWith(b);b.querySelector('strong').textContent='Start jam';box.querySelector('#v35HomeMetro').onclick=e=>{e.preventDefault();extra.metronome=!extra.metronome;V.persist();syncButtons()};b.onclick=async()=>{await ensureAudio();state.bpm=Math.max(40,Math.min(220,+box.querySelector('#v35HomeBpm').value||100));state.bars=+box.querySelector('#v35HomeBars').value;V.applyStyle(box.querySelector('#v35HomeStyle').value,false);V.persist();api.open();V.decorate?.()}}
function installTransport(){const t=document.querySelector('.v34-transport');if(!t)return;if(!document.querySelector('#v35MetroToggle')){const b=document.createElement('button');b.id='v35MetroToggle';b.className='v35-metro-toggle';b.type='button';b.onclick=()=>{extra.metronome=!extra.metronome;V.persist();syncButtons()};t.appendChild(b)}if(!document.querySelector('#v35StyleTop')){const l=document.createElement('label');l.className='v35-style-top';l.innerHTML=`<small>STYLE</small><select id="v35StyleTop">${Object.keys(STYLE_PRESETS).map(x=>`<option>${x}</option>`).join('')}</select>`;t.appendChild(l);l.querySelector('select').onchange=e=>{V.applyStyle(e.target.value,true);setTimeout(()=>V.decorate?.(),0)}}syncButtons()}
function decorate(){installTransport();syncButtons();window.MB_V36?.decorate?.()}
installTopbar();installDialog();installHome();decorate();const root=document.querySelector('#v34LooperScreen');if(root)new MutationObserver(()=>decorate()).observe(root,{childList:true,subtree:true});window.addEventListener('musicandbeats:v35change',syncButtons);V.openProjects=openProjects;V.decorate=decorate;
try{window.v7OpenProject=()=>openProjects(false);window.v7ProjectDialog=()=>document.querySelector('#v35ProjectsDialog')}catch{}
})();