/* Music & Beats V35 ARP and metronome scheduler. */
(()=>{
const V=window.MB_V35;if(!V||V.arpReady)return;V.arpReady=true;const {state,tracks,extra,ARP_PRESETS}=V;
function resolveChord(b){const root=b.dataset.root,quality=b.dataset.quality,base=noteMidi(root,3),preset=tracks.keys.sound,midis=preset==='Tanpura Drone'?[base-12,base,base+7,base+12]:voiced(chordIntervals('triad',quality),'open').map(x=>base+x);return{midis,preset}}
function scheduleVoice(m,p,v,start,dur,bus){const s=SOUND_PRESETS[p]||SOUND_PRESETS['Studio Grand'],g=ctx.createGain(),f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=s.filter;f.Q.value=s.q||.3;const a=Math.min(Math.max(.003,s.attack||.004),dur*.22),d=Math.min(Math.max(.015,s.decay||.2),dur*.28),r=Math.min(Math.max(.04,s.release||.3),dur*.45),ae=start+a,de=Math.min(start+dur*.58,ae+d),ra=Math.max(de,start+dur-r);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(Math.max(.001,s.gain*v),ae);g.gain.exponentialRampToValueAtTime(Math.max(.001,s.gain*s.sustain*v),de);g.gain.setValueAtTime(Math.max(.001,s.gain*s.sustain*v),ra);g.gain.exponentialRampToValueAtTime(.0001,start+dur);f.connect(g).connect(bus||synthBus);s.oscs.forEach(([type,semi,lev])=>{const o=ctx.createOscillator(),og=ctx.createGain();o.type=type;o.frequency.setValueAtTime(midiToFreq(m+semi),start);og.gain.value=lev;o.connect(og).connect(f);o.start(start);o.stop(start+dur+.03)})}
function bind(){const el=document.querySelector('#v34ChordPads');if(!el||el.dataset.v35ArpBound==='1')return;el.dataset.v35ArpBound='1';el.addEventListener('pointerdown',down,true);['pointerup','pointercancel','lostpointercapture'].forEach(n=>el.addEventListener(n,end,true))}
function down(e){const b=e.target.closest('.v34-performance-pad');if(!b||extra.arpPreset==='Off')return;e.preventDefault();e.stopImmediatePropagation();primeAudio();const r=resolveChord(b),h={button:b,midis:r.midis,preset:r.preset,arpPreset:extra.arpPreset,startedAt:ctx.currentTime,captureMeta:null,index:0,nextTime:ctx.currentTime+.01,timer:0};extra.liveArps.set(e.pointerId,h);b.classList.add('active');try{b.setPointerCapture(e.pointerId)}catch{};h.timer=setInterval(()=>liveTick(h),20)}
function liveTick(h){if(!ctx)return;if(!h.captureMeta&&state.recordingLane==='keys')h.captureMeta={startTime:state.recordStartTime,startStep:state.recordStartStep,boundary:state.recordStartTime+V.totalSteps()*V.stepSeconds()};const p=ARP_PRESETS[h.arpPreset];if(!p?.order)return;const rate=V.stepSeconds()*p.rateSteps;while(h.nextTime<ctx.currentTime+.08){const note=h.midis[p.order[h.index%p.order.length]%h.midis.length];scheduleVoice(note,h.preset,.72,h.nextTime,Math.max(.035,rate*p.gate),state.playbackBus||synthBus);h.index++;h.nextTime+=rate}}
function end(e){const h=extra.liveArps.get(e.pointerId);if(!h)return;e.preventDefault();e.stopImmediatePropagation();clearInterval(h.timer);capture(h,ctx.currentTime);extra.liveArps.delete(e.pointerId);h.button?.classList.remove('active')}
function capture(h,endTime){const m=h.captureMeta;if(!m)return;const sec=V.stepSeconds(),end=Math.min(endTime,m.boundary),start=Math.max(h.startedAt,m.startTime);let a=Math.round((start-m.startTime)/sec),b=Math.round((end-m.startTime)/sec);a=Math.max(0,Math.min(V.totalSteps()-1,a));b=Math.max(a+1,Math.min(V.totalSteps(),b));tracks.keys.events.push({step:V.wrapStep(m.startStep+a),durationSteps:Math.max(1,b-a),midis:[],preset:h.preset,v35Arp:{preset:h.arpPreset,notes:V.clone(h.midis)}});V.persist();const small=document.querySelector('.v34-track[data-lane="keys"] .v34-track-select small');if(small)small.textContent=`${tracks.keys.events.length} event${tracks.keys.events.length===1?'':'s'} loop`}
function scheduleArpEvent(e,when){const p=ARP_PRESETS[e.v35Arp?.preset],notes=e.v35Arp?.notes||[];if(!p?.order||!notes.length)return;const rate=V.stepSeconds()*p.rateSteps,dur=Math.max(V.stepSeconds(),(+e.durationSteps||1)*V.stepSeconds());let off=0,i=0;while(off<dur-.003&&i<128){const note=notes[p.order[i%p.order.length]%notes.length];scheduleVoice(note,e.preset||tracks.keys.sound,.72,when+off,Math.max(.035,rate*p.gate),state.playbackBus||synthBus);off+=rate;i++}}
function monitor(){if(!state.running){extra.lastAbs=0;extra.wasRunning=false;return}const abs=+state.absoluteStep||0;if(!extra.wasRunning){extra.lastAbs=0;extra.wasRunning=true}if(abs<extra.lastAbs)extra.lastAbs=0;if(state.countInSteps>0){extra.lastAbs=abs;return}if(abs>extra.lastAbs){const sec=V.stepSeconds(),next=state.nextStepTime;for(let n=extra.lastAbs;n<abs;n++){const when=next-(abs-n)*sec,step=V.wrapStep(n);if(extra.metronome&&step%4===0)click(when,step%16===0);tracks.keys.events.forEach(e=>{if(e.v35Arp&&V.wrapStep(e.step)===step)scheduleArpEvent(e,when)})}extra.lastAbs=abs}}
window.addEventListener('musicandbeats:v35keysready',bind);new MutationObserver(bind).observe(document.querySelector('#v34Workspace')||document.body,{childList:true,subtree:true});bind();setInterval(monitor,18);window.addEventListener('pagehide',()=>{extra.liveArps.forEach(h=>clearInterval(h.timer));extra.liveArps.clear()});
})();