/* Music & Beats V37 — live lead lane, backing mixer and project-aware mix recall. */
(()=>{
const V=window.MB_V35,api=window.MB_V34_LOOPER;if(!V||!api||window.MB_V37)return;
const {state,tracks}=api,PROJECTS_KEY='musicandbeats:v35:projects',SETTINGS_KEY='musicandbeats:v37:settings';
const defaults={mix:{beats:.86,keys:.80,bass:.84,lead:1.10},lead:{voice:'Bansuri Lead',key:'C',scale:'Major Pentatonic',octave:4}};
const v37={mix:{...defaults.mix},lead:{...defaults.lead},leadActive:false,leadHold:null,leadBus:null,leadComp:null,leadInput:null,lastSounds:{keys:null,bass:null},presetBase:new Map(),applying:false};
try{const x=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null');if(x?.mix)Object.assign(v37.mix,x.mix);if(x?.lead)Object.assign(v37.lead,x.lead)}catch{}
Object.keys(v37.mix).forEach(k=>v37.mix[k]=Math.max(0,Math.min(k==='lead'?1.4:1.2,+v37.mix[k]||defaults.mix[k])));v37.lead.octave=[3,4,5].includes(+v37.lead.octave)?+v37.lead.octave:4;
Object.entries(SOUND_PRESETS).forEach(([k,p])=>{if(Number.isFinite(p?.gain))v37.presetBase.set(k,p.gain)});
Object.assign(SOUND_PRESETS,{
  'Bansuri Lead':{oscs:[['sine',0,.72],['triangle',12,.13],['sine',19,.04]],attack:.035,decay:.12,sustain:.82,release:.20,filter:7600,q:.8,gain:.63},
  'Sitar Lead':{oscs:[['sawtooth',0,.20],['triangle',12,.38],['sine',24,.10],['sine',31,.04]],attack:.002,decay:.12,sustain:.34,release:.24,filter:8500,q:2.1,gain:.66},
  'Fusion Lead':{oscs:[['sawtooth',0,.28],['square',12,.08],['sine',12,.18]],attack:.008,decay:.10,sustain:.70,release:.18,filter:6900,q:1.0,gain:.56},
  'Glass Lead':{oscs:[['triangle',0,.48],['sine',12,.30],['sine',24,.08]],attack:.012,decay:.16,sustain:.68,release:.34,filter:9200,q:.55,gain:.58}
});
['Bansuri Lead','Sitar Lead','Fusion Lead','Glass Lead'].forEach(k=>v37.presetBase.set(k,SOUND_PRESETS[k].gain));
const LEAD_VOICES=['Bansuri Lead','Sitar Lead','Fusion Lead','Glass Lead'];
const SCALES={'Major Pentatonic':[0,2,4,7,9,12,14,16],'Minor Pentatonic':[0,3,5,7,10,12,15,17],Major:[0,2,4,5,7,9,11,12],'Natural Minor':[0,2,3,5,7,8,10,12]};
function clone(x){return JSON.parse(JSON.stringify(x))}
function persist(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({mix:v37.mix,lead:v37.lead}))}catch{}applyMix();syncMixer();}
function ensureBase(name){const p=SOUND_PRESETS[name];if(!p)return 1;if(!v37.presetBase.has(name)&&Number.isFinite(p.gain))v37.presetBase.set(name,p.gain);return v37.presetBase.get(name)||p.gain||1}
function applyPresetLevel(lane){const name=tracks[lane]?.sound;if(!name||!SOUND_PRESETS[name])return;const prev=v37.lastSounds[lane];if(prev&&prev!==name&&SOUND_PRESETS[prev]&&v37.presetBase.has(prev))SOUND_PRESETS[prev].gain=v37.presetBase.get(prev);SOUND_PRESETS[name].gain=ensureBase(name)*v37.mix[lane];v37.lastSounds[lane]=name}
function applyMix(){if(v37.applying)return;v37.applying=true;try{applyPresetLevel('keys');applyPresetLevel('bass');const duck=v37.leadHold?.voices?.length?true:false;if(state.playbackBus?.gain&&ctx){state.playbackBus.gain.cancelScheduledValues(ctx.currentTime);state.playbackBus.gain.setTargetAtTime(duck?.90:1,ctx.currentTime,.025)}if(state.beatBus?.gain&&ctx){const level=v37.mix.beats*(duck?.88:1);state.beatBus.gain.cancelScheduledValues(ctx.currentTime);state.beatBus.gain.setTargetAtTime(level,ctx.currentTime,.025)}if(v37.leadInput?.gain&&ctx){v37.leadInput.gain.cancelScheduledValues(ctx.currentTime);v37.leadInput.gain.setTargetAtTime(v37.mix.lead,ctx.currentTime,.02)}}catch{}finally{v37.applying=false}}
function ensureLeadBus(){if(!ctx)return null;if(v37.leadInput&&v37.leadInput.context===ctx)return v37.leadInput;try{v37.leadInput?.disconnect()}catch{}const input=ctx.createGain(),hp=ctx.createBiquadFilter(),presence=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor();input.gain.value=v37.mix.lead;hp.type='highpass';hp.frequency.value=115;presence.type='peaking';presence.frequency.value=2600;presence.Q.value=.75;presence.gain.value=3.2;comp.threshold.value=-18;comp.knee.value=12;comp.ratio.value=3;comp.attack.value=.004;comp.release.value=.12;input.connect(hp).connect(presence).connect(comp).connect(synthBus);v37.leadInput=input;v37.leadComp=comp;return input}
function startLeadVoice(m,preset,velocity=.88){const p=SOUND_PRESETS[preset]||SOUND_PRESETS['Bansuri Lead'],out=ensureLeadBus();if(!out||!ctx)return null;const f=ctx.createBiquadFilter(),g=ctx.createGain(),now=ctx.currentTime;f.type='lowpass';f.frequency.value=p.filter||7600;f.Q.value=p.q||.7;const peak=Math.max(.001,(p.gain||.6)*velocity),a=Math.max(.002,p.attack||.01),d=Math.max(.02,p.decay||.12);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(peak,now+a);g.gain.exponentialRampToValueAtTime(Math.max(.001,peak*(p.sustain??.72)),now+a+d);f.connect(g).connect(out);const oscs=(p.oscs||[['sine',0,1]]).map(([type,semi,lev])=>{const o=ctx.createOscillator(),og=ctx.createGain();o.type=type;o.frequency.setValueAtTime(midiToFreq(m+semi),now);og.gain.value=lev;o.connect(og).connect(f);o.start(now);return o});let stopped=false;return{stop(){if(stopped)return;stopped=true;const t=ctx.currentTime,r=Math.max(.05,Math.min(.45,p.release||.18));try{g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(Math.max(.001,g.gain.value||.02),t);g.gain.exponentialRampToValueAtTime(.0001,t+r)}catch{}oscs.forEach(o=>{try{o.stop(t+r+.03)}catch{}})}}}
function stopLead(){const h=v37.leadHold;if(!h)return;h.voices?.forEach(v=>v?.stop?.());h.pad?.classList.remove('active');v37.leadHold=null;applyMix()}
function leadNotes(){const ints=SCALES[v37.lead.scale]||SCALES['Major Pentatonic'],root=NOTES.indexOf(v37.lead.key),base=noteMidi('C',v37.lead.octave)+Math.max(0,root);return ints.map(x=>base+x)}
function renderLeadPads(){const host=document.querySelector('#v37LeadPads');if(!host)return;host.innerHTML=leadNotes().map((m,i)=>`<button class="v34-performance-pad v37-lead-pad" data-midi="${m}" type="button"><strong>${midiLabel(m)}</strong><small>${i+1}</small></button>`).join('');host.querySelectorAll('button').forEach(b=>{b.addEventListener('pointerdown',async e=>{e.preventDefault();await ensureAudio();primeAudio();stopLead();const voice=startLeadVoice(+b.dataset.midi,v37.lead.voice,.92);if(!voice)return;b.classList.add('active');v37.leadHold={pointerId:e.pointerId,pad:b,voices:[voice]};try{b.setPointerCapture(e.pointerId)}catch{}applyMix()});const end=e=>{if(v37.leadHold?.pointerId===e.pointerId)stopLead()};b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('lostpointercapture',end)})}
function renderLeadWorkspace(){const h=document.querySelector('#v34Workspace');if(!h)return;h.innerHTML=`<div class="v34-work-head"><div><span class="v34-kicker">LEAD</span><h2>Play over your loop</h2></div><small>Live only. Lead Focus gives this lane extra presence and gently ducks the backing while you play.</small></div><div class="v34-control-grid v37-lead-controls"><label>Voice<select id="v37LeadVoice">${LEAD_VOICES.map(x=>`<option ${x===v37.lead.voice?'selected':''}>${x}</option>`).join('')}</select></label><label>Key<select id="v37LeadKey">${NOTES.map(x=>`<option ${x===v37.lead.key?'selected':''}>${x}</option>`).join('')}</select></label><label>Scale<select id="v37LeadScale">${Object.keys(SCALES).map(x=>`<option ${x===v37.lead.scale?'selected':''}>${x}</option>`).join('')}</select></label><label>Octave<select id="v37LeadOctave">${[3,4,5].map(x=>`<option value="${x}" ${x===v37.lead.octave?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="v37-lead-tip"><strong>Lead Focus</strong><span>Presence EQ + light compression + automatic backing ducking</span></div><div id="v37LeadPads" class="v34-pad-grid v37-lead-grid"></div>`;h.querySelector('#v37LeadVoice').onchange=e=>{v37.lead.voice=e.target.value;persist()};h.querySelector('#v37LeadKey').onchange=e=>{v37.lead.key=e.target.value;persist();renderLeadPads()};h.querySelector('#v37LeadScale').onchange=e=>{v37.lead.scale=e.target.value;persist();renderLeadPads()};h.querySelector('#v37LeadOctave').onchange=e=>{v37.lead.octave=+e.target.value;persist();renderLeadPads()};renderLeadPads()}
function backingReady(){return tracks.keys.events.length>0&&tracks.bass.events.length>0}
function installLeadTrack(){const host=document.querySelector('#v34Tracks');if(!host)return;let card=document.querySelector('#v37LeadTrack');if(!card){card=document.createElement('article');card.id='v37LeadTrack';card.className='v37-track';card.innerHTML=`<button class="v37-track-select" type="button"><span class="v34-track-icon">🎶</span><span><strong>Lead</strong><small></small></span><i class="v34-track-led on"></i></button>`;host.appendChild(card);card.querySelector('button').onclick=e=>{e.preventDefault();stopLead();v37.leadActive=true;syncLeadTrack();renderLeadWorkspace();window.scrollTo({top:document.querySelector('#v34Workspace')?.offsetTop-110||0,behavior:'smooth'})}}const small=card.querySelector('small');if(small)small.textContent=backingReady()?'Ready to solo · live':'Live solo · build backing first';syncLeadTrack()}
function syncLeadTrack(){const card=document.querySelector('#v37LeadTrack');if(!card)return;card.classList.toggle('active',v37.leadActive);if(v37.leadActive)document.querySelectorAll('#v34Tracks .v34-track').forEach(x=>x.classList.remove('active'))}
function installMixer(){const tracksHost=document.querySelector('#v34Tracks'),workspace=document.querySelector('#v34Workspace');if(!tracksHost||!workspace)return;let mix=document.querySelector('#v37Mixer');if(!mix){mix=document.createElement('section');mix.id='v37Mixer';mix.className='v37-mixer';mix.innerHTML=`<header><div><span class="v34-kicker">MIX</span><strong>Backing levels</strong></div><small>Set the backing underneath your lead.</small></header><div class="v37-mix-grid">${[['beats','🥁','Beat'],['keys','🎹','Chords'],['bass','♩','Bass'],['lead','🎶','Lead']].map(([k,i,n])=>`<label data-mix="${k}"><span><b>${i} ${n}</b><output></output></span><input type="range" min="0" max="${k==='lead'?140:120}" value="${Math.round(v37.mix[k]*100)}"></label>`).join('')}</div>`;workspace.before(mix);mix.querySelectorAll('input').forEach(input=>input.oninput=e=>{const lane=e.target.closest('[data-mix]').dataset.mix;v37.mix[lane]=+e.target.value/100;persist()})}syncMixer()}
function syncMixer(){const mix=document.querySelector('#v37Mixer');if(!mix)return;mix.querySelectorAll('[data-mix]').forEach(row=>{const k=row.dataset.mix,input=row.querySelector('input'),out=row.querySelector('output'),value=Math.round(v37.mix[k]*100);if(document.activeElement!==input)input.value=value;if(out)out.textContent=`${value}%`})}
function decorateHome(){const chips=document.querySelector('.v34-home-chips');if(chips&&!chips.querySelector('[data-v37-lead]')){const s=document.createElement('span');s.dataset.v37Lead='1';s.textContent='🎶 Lead';chips.appendChild(s)}const p=document.querySelector('.v34-home-card>p');if(p&&p.textContent.includes('Beats, chords and bass'))p.textContent='Build beats, chords and bass into one synced backing loop, then play lead over it.'}
function decorate(){installLeadTrack();installMixer();decorateHome();if(v37.leadActive){syncLeadTrack();const h=document.querySelector('#v34Workspace');if(h&&!h.querySelector('#v37LeadPads'))renderLeadWorkspace()}applyMix()}
document.addEventListener('click',e=>{if(e.target.closest?.('#v34Tracks .v34-track-select')){v37.leadActive=false;stopLead();setTimeout(syncLeadTrack,0)}if(e.target.closest?.('#homeBtn,#v34Transport')&&!state.running)stopLead()},true);
window.addEventListener('pagehide',stopLead);window.addEventListener('blur',stopLead);
const baseSave=V.saveProject.bind(V),baseLoad=V.loadProject.bind(V),baseNew=V.newProject.bind(V);
V.saveProject=function(...args){const item=baseSave(...args);try{const list=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]'),x=list.find(p=>p.id===item?.id);if(x?.data){x.data.v37={mix:clone(v37.mix),lead:clone(v37.lead)};localStorage.setItem(PROJECTS_KEY,JSON.stringify(list))}}catch{}return item};
V.loadProject=function(id){let saved=null;try{saved=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]').find(p=>p.id===id)?.data?.v37||null}catch{}stopLead();v37.leadActive=false;const ok=baseLoad(id);Object.assign(v37.mix,defaults.mix,saved?.mix||{});Object.assign(v37.lead,defaults.lead,saved?.lead||{});persist();setTimeout(decorate,0);return ok};
V.newProject=function(){stopLead();v37.leadActive=false;const out=baseNew();Object.assign(v37.mix,defaults.mix);Object.assign(v37.lead,defaults.lead);persist();setTimeout(decorate,0);return out};
const observer=new MutationObserver(()=>decorate());observer.observe(document.body,{childList:true,subtree:true});setInterval(applyMix,120);
window.MB_V37={version:'v37',mix:v37.mix,lead:v37.lead,stopLead,applyMix,decorate};V.version='v37';document.documentElement.classList.add('mb-v37');document.body.classList.add('mb-v37');decorate();
})();