/* Music & Beats V38 — true lead keyboard/keytar, sample-backed voices and deep FX. */
(()=>{
  const V=window.MB_V35, api=window.MB_V34_LOOPER, V37=window.MB_V37;
  if(!V||!api||!V37||window.MB_V38)return;
  const SETTINGS='musicandbeats:v38:settings', PROJECTS='musicandbeats:v35:projects';
  const SYNTH_VOICES=['Bansuri Lead','Sitar Lead','Fusion Lead','Glass Lead'];
  const SAMPLE_VOICES={
    'Sample Grand':{file:'0000_GeneralUserGS_sf2_file.js',variable:'_tone_0000_GeneralUserGS_sf2_file'},
    'Sample EP':{file:'0040_GeneralUserGS_sf2_file.js',variable:'_tone_0040_GeneralUserGS_sf2_file'},
    'Sample Reed Organ':{file:'0200_GeneralUserGS_sf2_file.js',variable:'_tone_0200_GeneralUserGS_sf2_file'},
    'Sample Flute':{file:'0730_GeneralUserGS_sf2_file.js',variable:'_tone_0730_GeneralUserGS_sf2_file'},
    'Sample Shakuhachi':{file:'0770_GeneralUserGS_sf2_file.js',variable:'_tone_0770_GeneralUserGS_sf2_file'},
    'Sample Sitar':{file:'1040_GeneralUserGS_sf2_file.js',variable:'_tone_1040_GeneralUserGS_sf2_file'}
  };
  const ALL_VOICES=[...SYNTH_VOICES,...Object.keys(SAMPLE_VOICES)];
  const FX_PRESETS={
    'Dry':{mod:'Off',drive:'Off',delay:'Off',space:'Off',intensity:20,wet:0,tone:82},
    'Studio':{mod:'Off',drive:'Warm',delay:'Slap',space:'Room',intensity:28,wet:20,tone:76},
    'Wide Chorus':{mod:'Chorus',drive:'Off',delay:'Off',space:'Plate',intensity:55,wet:38,tone:78},
    'Deep Phaser':{mod:'Phaser',drive:'Warm',delay:'Tape',space:'Plate',intensity:62,wet:42,tone:72},
    'Tremolo':{mod:'Tremolo',drive:'Off',delay:'Off',space:'Room',intensity:58,wet:30,tone:80},
    'Vibrato':{mod:'Vibrato',drive:'Off',delay:'Slap',space:'Plate',intensity:44,wet:30,tone:82},
    'Auto Wah':{mod:'Auto Wah',drive:'Warm',delay:'Off',space:'Room',intensity:64,wet:34,tone:70},
    'Warm Drive':{mod:'Off',drive:'Warm',delay:'Slap',space:'Room',intensity:48,wet:22,tone:65},
    'Crunch':{mod:'Off',drive:'Crunch',delay:'Tape',space:'Plate',intensity:60,wet:30,tone:58},
    'Fuzz Lead':{mod:'Off',drive:'Fuzz',delay:'Stereo',space:'Hall',intensity:72,wet:38,tone:52},
    'Slapback':{mod:'Off',drive:'Warm',delay:'Slap',space:'Room',intensity:42,wet:34,tone:74},
    'Tape Echo':{mod:'Chorus',drive:'Warm',delay:'Tape',space:'Plate',intensity:56,wet:46,tone:62},
    'Ping Pong':{mod:'Off',drive:'Off',delay:'Ping Pong',space:'Hall',intensity:60,wet:48,tone:78},
    'Plate':{mod:'Off',drive:'Off',delay:'Off',space:'Plate',intensity:48,wet:44,tone:82},
    'Hall':{mod:'Off',drive:'Off',delay:'Stereo',space:'Hall',intensity:52,wet:50,tone:80},
    'Cathedral':{mod:'Chorus',drive:'Off',delay:'Stereo',space:'Cathedral',intensity:70,wet:66,tone:74},
    'Dream Space':{mod:'Chorus',drive:'Off',delay:'Ping Pong',space:'Cathedral',intensity:76,wet:70,tone:76},
    'Lo-Fi':{mod:'Tremolo',drive:'Crunch',delay:'Tape',space:'Room',intensity:46,wet:32,tone:34},
    'Indian Space':{mod:'Vibrato',drive:'Warm',delay:'Tape',space:'Hall',intensity:50,wet:48,tone:72},
    'Fusion Solo':{mod:'Chorus',drive:'Crunch',delay:'Stereo',space:'Plate',intensity:58,wet:40,tone:68}
  };
  const state={layout:'Piano',startOctave:4,displayOctaves:innerWidth<520?1:2,voice:'Bansuri Lead',fxPreset:'Studio',fx:{...FX_PRESETS.Studio},holds:new Map(),pending:new Set(),buffers:new WeakMap(),scripts:new Map(),input:null,output:null,nodes:[],lfos:[],rendering:false};
  try{const s=JSON.parse(localStorage.getItem(SETTINGS)||'null');if(s){Object.assign(state,{layout:s.layout||state.layout,startOctave:+s.startOctave||4,displayOctaves:+s.displayOctaves||state.displayOctaves,voice:s.voice||state.voice,fxPreset:s.fxPreset||state.fxPreset});if(s.fx)state.fx={...state.fx,...s.fx}}}catch{}
  if(!ALL_VOICES.includes(state.voice))state.voice='Bansuri Lead';
  state.startOctave=Math.max(1,Math.min(6,state.startOctave));state.displayOctaves=[1,2,3].includes(state.displayOctaves)?state.displayOctaves:1;
  const clone=x=>JSON.parse(JSON.stringify(x));
  function persist(){try{localStorage.setItem(SETTINGS,JSON.stringify({layout:state.layout,startOctave:state.startOctave,displayOctaves:state.displayOctaves,voice:state.voice,fxPreset:state.fxPreset,fx:state.fx}))}catch{}}
  function audioReady(){return typeof ctx!=='undefined'&&ctx}
  function stopAll(){for(const h of state.holds.values())h.stop?.();state.holds.clear();state.pending.clear();window.MB_V38_LEAD_ACTIVE=false;syncDuck();document.querySelectorAll('.v38-key.active').forEach(k=>k.classList.remove('active'))}
  function syncDuck(){if(!audioReady())return;const on=state.holds.size>0||state.pending.size>0;window.MB_V38_LEAD_ACTIVE=on;try{if(api.state.playbackBus?.gain){api.state.playbackBus.gain.cancelScheduledValues(ctx.currentTime);api.state.playbackBus.gain.setTargetAtTime(on?.90:1,ctx.currentTime,.025)}if(api.state.beatBus?.gain){const base=V37.mix?.beats??.86;api.state.beatBus.gain.cancelScheduledValues(ctx.currentTime);api.state.beatBus.gain.setTargetAtTime(base*(on?.88:1),ctx.currentTime,.025)}}catch{}}
  function cleanGraph(){for(const lfo of state.lfos){try{lfo.stop()}catch{}}state.lfos=[];for(const n of state.nodes){try{n.disconnect()}catch{}}state.nodes=[];state.input=state.output=null}
  function curve(amount){const n=2048,a=Math.max(0,amount),arr=new Float32Array(n);for(let i=0;i<n;i++){const x=i*2/n-1;arr[i]=(1+a)*x/(1+a*Math.abs(x))}return arr}
  function impulse(seconds,decay){const rate=ctx.sampleRate,len=Math.max(1,rate*seconds|0),b=ctx.createBuffer(2,len,rate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)}return b}
  function buildFX(){if(!audioReady())return null;stopAll();cleanGraph();const f=state.fx,intensity=(+f.intensity||0)/100,wet=(+f.wet||0)/100;
    const input=ctx.createGain(),tone=ctx.createBiquadFilter(),drive=ctx.createWaveShaper();tone.type='lowpass';tone.frequency.value=1800+Math.pow((+f.tone||70)/100,1.5)*15000;tone.Q.value=.25;const driveAmt=f.drive==='Warm'?1.2:f.drive==='Crunch'?4:f.drive==='Fuzz'?12:0;drive.curve=curve(driveAmt);drive.oversample='2x';input.connect(tone).connect(drive);let current=drive;state.nodes.push(input,tone,drive);
    if(f.mod!=='Off'){
      if(f.mod==='Chorus'||f.mod==='Vibrato'){
        const dry=ctx.createGain(),del=ctx.createDelay(.06),wg=ctx.createGain(),sum=ctx.createGain(),lfo=ctx.createOscillator(),lg=ctx.createGain();dry.gain.value=f.mod==='Vibrato'?.18:.72;wg.gain.value=f.mod==='Vibrato'?.92:.48;del.delayTime.value=f.mod==='Vibrato'?.004:.014;lfo.frequency.value=f.mod==='Vibrato'?4.8:1.1;lg.gain.value=(f.mod==='Vibrato'?.0025:.006)*intensity;lfo.connect(lg).connect(del.delayTime);current.connect(dry).connect(sum);current.connect(del).connect(wg).connect(sum);lfo.start();state.lfos.push(lfo);state.nodes.push(dry,del,wg,sum,lg);current=sum;
      }else if(f.mod==='Tremolo'){
        const g=ctx.createGain(),lfo=ctx.createOscillator(),lg=ctx.createGain();g.gain.value=1-intensity*.35;lfo.frequency.value=3.2+intensity*4;lg.gain.value=intensity*.34;lfo.connect(lg).connect(g.gain);current.connect(g);lfo.start();state.lfos.push(lfo);state.nodes.push(g,lg);current=g;
      }else if(f.mod==='Phaser'){
        const sum=ctx.createGain();let chain=current;for(let i=0;i<4;i++){const a=ctx.createBiquadFilter();a.type='allpass';a.frequency.value=550+i*420;a.Q.value=1.1+intensity*4;chain.connect(a);chain=a;state.nodes.push(a)}const dry=ctx.createGain(),wg=ctx.createGain();dry.gain.value=.64;wg.gain.value=.58;current.connect(dry).connect(sum);chain.connect(wg).connect(sum);state.nodes.push(sum,dry,wg);current=sum;
      }else if(f.mod==='Auto Wah'){
        const wah=ctx.createBiquadFilter(),lfo=ctx.createOscillator(),lg=ctx.createGain();wah.type='bandpass';wah.frequency.value=700+intensity*600;wah.Q.value=2.5+intensity*5;lfo.frequency.value=1.2+intensity*2.6;lg.gain.value=500+intensity*1600;lfo.connect(lg).connect(wah.frequency);current.connect(wah);lfo.start();state.lfos.push(lfo);state.nodes.push(wah,lg);current=wah;
      }
    }
    const delayDry=ctx.createGain(),delayWet=ctx.createGain(),delay=ctx.createDelay(1.2),feedback=ctx.createGain(),delaySum=ctx.createGain();delayDry.gain.value=1;delayWet.gain.value=f.delay==='Off'?0:Math.min(.72,wet*.85+.08);const ds=f.delay==='Slap'?.09:f.delay==='Tape'?.29:f.delay==='Stereo'?.38:f.delay==='Ping Pong'?.46:.01;delay.delayTime.value=ds;feedback.gain.value=f.delay==='Off'?0:Math.min(.68,.18+intensity*.45);current.connect(delayDry).connect(delaySum);current.connect(delay);delay.connect(feedback).connect(delay);let delayOut=delay;if((f.delay==='Stereo'||f.delay==='Ping Pong')&&ctx.createStereoPanner){const p=ctx.createStereoPanner();p.pan.value=f.delay==='Ping Pong'?.72:.38;delay.connect(p);delayOut=p;state.nodes.push(p)}delayOut.connect(delayWet).connect(delaySum);state.nodes.push(delayDry,delayWet,delay,feedback,delaySum);current=delaySum;
    const revDry=ctx.createGain(),revWet=ctx.createGain(),conv=ctx.createConvolver(),revSum=ctx.createGain();let sec=f.space==='Room'?.7:f.space==='Plate'?1.3:f.space==='Hall'?2.4:f.space==='Cathedral'?4.2:.2,dec=f.space==='Cathedral'?3.2:f.space==='Hall'?2.8:2.2;conv.buffer=impulse(sec,dec);revDry.gain.value=1;revWet.gain.value=f.space==='Off'?0:Math.min(.78,wet);current.connect(revDry).connect(revSum);current.connect(conv).connect(revWet).connect(revSum);state.nodes.push(revDry,revWet,conv,revSum);current=revSum;
    const hp=ctx.createBiquadFilter(),presence=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor(),out=ctx.createGain();hp.type='highpass';hp.frequency.value=90;presence.type='peaking';presence.frequency.value=2700;presence.Q.value=.75;presence.gain.value=3.4;comp.threshold.value=-18;comp.knee.value=10;comp.ratio.value=3;comp.attack.value=.004;comp.release.value=.12;out.gain.value=V37.mix?.lead??1.1;current.connect(hp).connect(presence).connect(comp).connect(out).connect(synthBus);state.nodes.push(hp,presence,comp,out);state.input=input;state.output=out;return input
  }
  function output(){if(!state.input||state.input.context!==ctx)buildFX();return state.input}
  function loadSample(name){const spec=SAMPLE_VOICES[name];if(!spec)return Promise.resolve(null);if(window[spec.variable])return Promise.resolve(window[spec.variable]);if(state.scripts.has(name))return state.scripts.get(name);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`https://cdn.jsdelivr.net/gh/surikov/webaudiofontdata@master/sound/${spec.file}`;s.crossOrigin='anonymous';s.onload=()=>resolve(window[spec.variable]||null);s.onerror=()=>reject(new Error(`Could not load ${name}`));document.head.appendChild(s)}).catch(e=>{console.warn(e);return null});state.scripts.set(name,p);return p}
  function zoneFor(preset,midi){return preset?.zones?.find(z=>midi>=z.keyRangeLow&&midi<=z.keyRangeHigh)||preset?.zones?.reduce((a,z)=>Math.abs(midi-(z.keyRangeLow+z.keyRangeHigh)/2)<Math.abs(midi-(a.keyRangeLow+a.keyRangeHigh)/2)?z:a,preset.zones[0])}
  async function zoneBuffer(zone){if(!zone?.file||!audioReady())return null;if(state.buffers.has(zone))return state.buffers.get(zone);const bytes=Uint8Array.from(atob(zone.file),c=>c.charCodeAt(0)).buffer;const p=ctx.decodeAudioData(bytes.slice(0)).catch(()=>null);state.buffers.set(zone,p);return p}
  async function sampleVoice(midi,name){const preset=await loadSample(name),zone=zoneFor(preset,midi),buffer=await zoneBuffer(zone),dest=output();if(!buffer||!zone||!dest)return null;const src=ctx.createBufferSource(),g=ctx.createGain(),now=ctx.currentTime,base=(+zone.originalPitch||6000)/100+(+zone.coarseTune||0)+(+zone.fineTune||0)/100;src.buffer=buffer;src.playbackRate.value=Math.pow(2,(midi-base)/12);if(+zone.loopStart>=0&&+zone.loopEnd>+zone.loopStart){src.loop=true;src.loopStart=zone.loopStart/(zone.sampleRate||buffer.sampleRate);src.loopEnd=zone.loopEnd/(zone.sampleRate||buffer.sampleRate)}g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.86,now+.008);src.connect(g).connect(dest);src.start(now,Math.max(0,+zone.delay||0));let stopped=false;return{stop(){if(stopped)return;stopped=true;const t=ctx.currentTime;try{g.gain.cancelScheduledValues(t);g.gain.setTargetAtTime(.0001,t,.045);src.stop(t+.18)}catch{}}}}
  function synthVoice(midi,name){const p=SOUND_PRESETS[name]||SOUND_PRESETS['Bansuri Lead'],dest=output();if(!dest)return null;const f=ctx.createBiquadFilter(),g=ctx.createGain(),now=ctx.currentTime;f.type='lowpass';f.frequency.value=p.filter||7600;f.Q.value=p.q||.7;const peak=(p.gain||.6)*.93;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.001,peak),now+Math.max(.002,p.attack||.01));g.gain.exponentialRampToValueAtTime(Math.max(.001,peak*(p.sustain??.72)),now+Math.max(.05,(p.attack||.01)+(p.decay||.12)));f.connect(g).connect(dest);const os=(p.oscs||[['sine',0,1]]).map(([type,semi,lev])=>{const o=ctx.createOscillator(),og=ctx.createGain();o.type=type;o.frequency.value=midiToFreq(midi+semi);og.gain.value=lev;o.connect(og).connect(f);o.start();return o});let stopped=false;return{stop(){if(stopped)return;stopped=true;const t=ctx.currentTime,r=Math.max(.05,Math.min(.45,p.release||.18));try{g.gain.cancelScheduledValues(t);g.gain.setTargetAtTime(.0001,t,r/3);os.forEach(o=>o.stop(t+r+.04))}catch{}}}}
  async function press(event,key){event.preventDefault();await ensureAudio();primeAudio();const id=event.pointerId,midi=+key.dataset.midi;state.pending.add(id);key.classList.add('active');syncDuck();let voice=SAMPLE_VOICES[state.voice]?await sampleVoice(midi,state.voice):synthVoice(midi,state.voice);state.pending.delete(id);if(!key.isConnected||!voice){key.classList.remove('active');syncDuck();return}state.holds.set(id,{key,voice,stop(){voice.stop?.();key.classList.remove('active')}});try{key.setPointerCapture(id)}catch{}syncDuck()}
  function release(event){const id=event.pointerId,h=state.holds.get(id);state.pending.delete(id);if(h){h.stop();state.holds.delete(id)}syncDuck()}
  function keyboardHTML(){const oct=state.displayOctaves,start=12*(state.startOctave+1),white=[];for(let o=0;o<oct;o++)for(const s of [0,2,4,5,7,9,11])white.push(start+o*12+s);white.push(start+oct*12);const blacks=[];for(let o=0;o<oct;o++){const base=o*7;[[1,0],[3,1],[6,3],[8,4],[10,5]].forEach(([semi,after])=>blacks.push({m:start+o*12+semi,left:((base+after+.68)/white.length)*100}))}return `<div class="v38-key-scroll ${state.layout==='Keytar'?'keytar':''}"><div class="v38-keyboard" style="--white-count:${white.length}"><div class="v38-whites">${white.map(m=>`<button class="v38-key white" data-midi="${m}" type="button"><span>${midiLabel(m)}</span></button>`).join('')}</div>${blacks.map(x=>`<button class="v38-key black" data-midi="${x.m}" style="left:${x.left}%" type="button"><span>${midiLabel(x.m)}</span></button>`).join('')}</div></div>`}
  function bindKeys(){document.querySelectorAll('#v38Keyboard .v38-key').forEach(k=>{k.addEventListener('pointerdown',e=>press(e,k));k.addEventListener('pointerup',release);k.addEventListener('pointercancel',release);k.addEventListener('lostpointercapture',release)})}
  function applyPreset(name){const p=FX_PRESETS[name];if(!p)return;state.fxPreset=name;state.fx={...p};persist();if(audioReady())buildFX();renderLead()}
  function fxControls(){return `<details class="v38-fx" open><summary><span><b>Effects rack</b><small>${state.fx.mod} · ${state.fx.drive} · ${state.fx.delay} · ${state.fx.space}</small></span><i>⌄</i></summary><div class="v38-fx-grid"><label>FX preset<select id="v38FxPreset">${Object.keys(FX_PRESETS).map(n=>`<option ${n===state.fxPreset?'selected':''}>${n}</option>`).join('')}</select></label><label>Modulation<select id="v38Mod">${['Off','Chorus','Phaser','Tremolo','Vibrato','Auto Wah'].map(n=>`<option ${n===state.fx.mod?'selected':''}>${n}</option>`).join('')}</select></label><label>Drive<select id="v38Drive">${['Off','Warm','Crunch','Fuzz'].map(n=>`<option ${n===state.fx.drive?'selected':''}>${n}</option>`).join('')}</select></label><label>Delay<select id="v38Delay">${['Off','Slap','Tape','Stereo','Ping Pong'].map(n=>`<option ${n===state.fx.delay?'selected':''}>${n}</option>`).join('')}</select></label><label>Space<select id="v38Space">${['Off','Room','Plate','Hall','Cathedral'].map(n=>`<option ${n===state.fx.space?'selected':''}>${n}</option>`).join('')}</select></label><label>Intensity <output>${state.fx.intensity}%</output><input id="v38Intensity" type="range" min="0" max="100" value="${state.fx.intensity}"></label><label>Wet <output>${state.fx.wet}%</output><input id="v38Wet" type="range" min="0" max="100" value="${state.fx.wet}"></label><label>Tone <output>${state.fx.tone}%</output><input id="v38Tone" type="range" min="0" max="100" value="${state.fx.tone}"></label></div></details>`}
  function renderLead(){const w=document.querySelector('#v34Workspace');if(!w)return;stopAll();w.innerHTML=`<div class="v34-work-head"><div><span class="v34-kicker">LEAD INSTRUMENT</span><h2>${state.layout==='Keytar'?'Keytar':'Performance keys'}</h2></div><small>Chromatic individual keys — play real melodies, chords and runs with multi-touch.</small></div><div class="v38-toolbar"><label>Instrument<select id="v38Voice">${ALL_VOICES.map(n=>`<option ${n===state.voice?'selected':''}>${n}</option>`).join('')}</select></label><label>Layout<select id="v38Layout"><option ${state.layout==='Piano'?'selected':''}>Piano</option><option ${state.layout==='Keytar'?'selected':''}>Keytar</option></select></label><label>Start octave<select id="v38StartOct">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===state.startOctave?'selected':''}>${n}</option>`).join('')}</select></label><label>Displayed octaves<select id="v38Octaves">${[1,2,3].map(n=>`<option value="${n}" ${n===state.displayOctaves?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="v38-sample-status" id="v38SampleStatus">${SAMPLE_VOICES[state.voice]?'Sampled GeneralUser GS voice · loads once, then browser-cached':'Realtime Web Audio synth voice'}</div>${fxControls()}<div id="v38Keyboard">${keyboardHTML()}</div>`;bindLeadControls();bindKeys();window.MB_V39?.applyCollapse?.('lead');window.MB_V39?.decorateLead?.();if(window.MB_V39?.sampleManager){window.MB_V39.sampleManager.preloadVoice(state.voice)}else if(SAMPLE_VOICES[state.voice]){const status=w.querySelector('#v38SampleStatus');loadSample(state.voice).then(p=>{if(status&&p)status.textContent='Sample ready · GeneralUser GS / WebAudioFont data'})}}
  function rebuildFXFromControl(){state.fxPreset='Custom';persist();if(audioReady())buildFX();const s=document.querySelector('.v38-fx summary small');if(s)s.textContent=`${state.fx.mod} · ${state.fx.drive} · ${state.fx.delay} · ${state.fx.space}`}
  function bindLeadControls(){const q=id=>document.querySelector(id);q('#v38Voice').onchange=e=>{state.voice=e.target.value;persist();renderLead()};q('#v38Layout').onchange=e=>{state.layout=e.target.value;persist();renderLead()};q('#v38StartOct').onchange=e=>{state.startOctave=+e.target.value;persist();renderLead()};q('#v38Octaves').onchange=e=>{state.displayOctaves=+e.target.value;persist();renderLead()};q('#v38FxPreset').onchange=e=>applyPreset(e.target.value);[['#v38Mod','mod'],['#v38Drive','drive'],['#v38Delay','delay'],['#v38Space','space']].forEach(([id,k])=>q(id).onchange=e=>{state.fx[k]=e.target.value;rebuildFXFromControl()});[['#v38Intensity','intensity'],['#v38Wet','wet'],['#v38Tone','tone']].forEach(([id,k])=>q(id).oninput=e=>{state.fx[k]=+e.target.value;e.target.closest('label').querySelector('output').textContent=`${e.target.value}%`;rebuildFXFromControl()})}
  function ownLeadCard(){const b=document.querySelector('#v37LeadTrack .v37-track-select');if(!b)return;const small=b.querySelector('small');if(small)small.textContent='Piano / keytar · sampled voices · deep FX'}
  document.addEventListener('click',e=>{const b=e.target.closest?.('#v37LeadTrack .v37-track-select');if(!b)return;e.preventDefault();e.stopPropagation();document.querySelectorAll('#v34Tracks .v34-track,#v37LeadTrack').forEach(x=>x.classList.remove('active'));document.querySelector('#v37LeadTrack')?.classList.add('active');renderLead();window.MB_V39?.applyCollapse?.('lead');window.MB_V39?.decorateLead?.()},true);
  function decorate(){ownLeadCard();const home=document.querySelector('.v34-home-card>p');if(home&&home.textContent.includes('play lead over it'))home.textContent='Build the backing loop, then play a real piano/keytar lead over it with sampled voices and effects.';}
  const baseSave=V.saveProject.bind(V),baseLoad=V.loadProject.bind(V),baseNew=V.newProject.bind(V);
  V.saveProject=function(...args){const item=baseSave(...args);try{const list=JSON.parse(localStorage.getItem(PROJECTS)||'[]'),x=list.find(p=>p.id===item?.id);if(x?.data){x.data.v38={layout:state.layout,startOctave:state.startOctave,displayOctaves:state.displayOctaves,voice:state.voice,fxPreset:state.fxPreset,fx:clone(state.fx)};localStorage.setItem(PROJECTS,JSON.stringify(list))}}catch{}return item};
  V.loadProject=function(id){let saved=null;try{saved=JSON.parse(localStorage.getItem(PROJECTS)||'[]').find(p=>p.id===id)?.data?.v38||null}catch{};stopAll();const out=baseLoad(id);if(saved){state.layout=saved.layout||'Piano';state.startOctave=+saved.startOctave||4;state.displayOctaves=+saved.displayOctaves||1;state.voice=ALL_VOICES.includes(saved.voice)?saved.voice:'Bansuri Lead';state.fxPreset=saved.fxPreset||'Studio';state.fx={...(FX_PRESETS[state.fxPreset]||FX_PRESETS.Studio),...(saved.fx||{})}}persist();setTimeout(decorate,0);return out};
  V.newProject=function(){stopAll();const out=baseNew();Object.assign(state,{layout:'Piano',startOctave:4,displayOctaves:innerWidth<520?1:2,voice:'Bansuri Lead',fxPreset:'Studio',fx:{...FX_PRESETS.Studio}});persist();setTimeout(decorate,0);return out};
  new MutationObserver(()=>{if(!state.rendering)requestAnimationFrame(decorate)}).observe(document.body,{childList:true,subtree:true});
  setInterval(()=>{if(state.output&&audioReady()){try{state.output.gain.setTargetAtTime(V37.mix?.lead??1.1,ctx.currentTime,.03)}catch{}}if(state.holds.size||state.pending.size)syncDuck()},45);
  window.addEventListener('pagehide',stopAll);window.addEventListener('blur',stopAll);
  window.MB_V38={version:'v38',state,renderLead,stopAll,FX_PRESETS,SAMPLE_VOICES};V.version='v38';document.documentElement.classList.add('mb-v38');document.body.classList.add('mb-v38');decorate();
})();