/* Music & Beats V4: sample-accurate loop capture, phase-locked playback, expression controls and instrument skins. */
const V4_PLAY_EXPR={velocity:100/127,sustain:.8,tone:7000,space:.18};
const V4_BASS_PRESETS=['Sub Bass','Finger Bass','Pick Bass','Upright Bass','Analog Pulse Bass','FM Round Bass'];
const V4_SKINS={grand:{file:'assets/instruments/grand-piano.svg',label:'ACOUSTIC GRAND',accent:'#c3b7ff'},ep:{file:'assets/instruments/electric-piano.svg',label:'ELECTRIC KEYS',accent:'#7dd3fc'},organ:{file:'assets/instruments/organ.svg',label:'TONEWHEEL ORGAN',accent:'#fb7185'},synth:{file:'assets/instruments/synth.svg',label:'SYNTHESIZER',accent:'#a78bfa'},pad:{file:'assets/instruments/pad.svg',label:'ATMOSPHERIC PAD',accent:'#5eead4'},bass:{file:'assets/instruments/bass.svg',label:'BASS INSTRUMENT',accent:'#fbbf24'}};
let v4WorkletReady=false,v4CaptureNode=null,v4SilentGain=null;
Object.assign(SOUND_PRESETS,{
'Finger Bass':{oscs:[['triangle',-12,.42],['sawtooth',0,.22],['sine',12,.08]],attack:.005,decay:.18,sustain:.58,release:.2,filter:1850,q:.8,gain:.66},
'Pick Bass':{oscs:[['sawtooth',-12,.36],['square',0,.15],['triangle',12,.08]],attack:.002,decay:.12,sustain:.46,release:.14,filter:2600,q:1.15,gain:.62},
'Upright Bass':{oscs:[['triangle',-12,.46],['sine',0,.24],['triangle',12,.05]],attack:.014,decay:.44,sustain:.38,release:.5,filter:1450,q:.5,gain:.7},
'Analog Pulse Bass':{oscs:[['square',-12,.34],['sawtooth',0,.22],['sine',-24,.18]],attack:.006,decay:.2,sustain:.62,release:.25,filter:1050,q:1.5,gain:.62},
'FM Round Bass':{oscs:[['sine',-12,.5],['sine',7,.13],['triangle',12,.1]],attack:.003,decay:.3,sustain:.5,release:.3,filter:2300,q:.7,gain:.72}
});
function v4LayerExpr(layer){if(!layer.expression)layer.expression={velocity:100/127,sustain:.8,tone:7000,space:.18};return layer.expression}
function v4Expr(){return currentScreen==='record'&&session.layers.length?v4LayerExpr(sessionLayer()):V4_PLAY_EXPR}
function v4SkinFor(preset,source='keys'){if(source==='bass'||V4_BASS_PRESETS.includes(preset))return V4_SKINS.bass;if(/Grand/i.test(preset))return V4_SKINS.grand;if(/Velvet|Wurli/i.test(preset))return V4_SKINS.ep;if(/Organ|Tonewheel/i.test(preset))return V4_SKINS.organ;if(/Pad|Choir/i.test(preset))return V4_SKINS.pad;return V4_SKINS.synth}
startVoice=function(m,p='Studio Grand',v=.86){primeAudio();const s=SOUND_PRESETS[p]||SOUND_PRESETS['Studio Grand'],x=v4Expr(),now=ctx.currentTime;if(reverbWet)reverbWet.gain.setTargetAtTime(x.space,now,.02);const g=ctx.createGain(),f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=Math.min(16000,Math.max(500,x.tone||s.filter));f.Q.value=s.q||.3;const velocity=clamp((v||.86)*(x.velocity||.78),.03,1.25),peak=Math.max(.001,s.gain*velocity);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(peak,now+s.attack+.004);g.gain.exponentialRampToValueAtTime(Math.max(.001,peak*s.sustain),now+s.attack+s.decay+.01);f.connect(g).connect(synthBus);const os=s.oscs.map(([type,semi,lev])=>{const o=ctx.createOscillator(),og=ctx.createGain();o.type=type;o.frequency.value=midiToFreq(m+semi);og.gain.value=lev;o.connect(og).connect(f);o.start(now);return o});let stopped=false;const release=Math.max(.04,(x.sustain||.8)*.72+s.release*.35);const voice={stop(){if(stopped)return;stopped=true;const t=ctx.currentTime;try{g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(Math.max(.0001,g.gain.value),t);g.gain.exponentialRampToValueAtTime(.0001,t+release);os.forEach(o=>o.stop(t+release+.04))}catch{}activeVoices.delete(voice);updateVoiceBadges()}};activeVoices.add(voice);updateVoiceBadges();return voice};
function v4ExpressionMarkup(prefix,expr){const vel=Math.round((expr.velocity||.78)*127),sus=expr.sustain??.8,tone=expr.tone??7000,space=Math.round((expr.space??.18)*100);return `<div class="expression-strip" data-expression="${prefix}"><label><span>Velocity <b data-out="velocity">${vel}</b></span><input data-expr="velocity" type="range" min="20" max="127" value="${vel}"></label><label><span>Sustain <b data-out="sustain">${sus.toFixed(2)}s</b></span><input data-expr="sustain" type="range" min="0.05" max="3" step="0.05" value="${sus}"></label><label><span>Tone <b data-out="tone">${(tone/1000).toFixed(1)}k</b></span><input data-expr="tone" type="range" min="700" max="12000" step="100" value="${tone}"></label><label><span>Space <b data-out="space">${space}%</b></span><input data-expr="space" type="range" min="0" max="65" value="${space}"></label></div>`}
function v4BindExpression(el,expr){if(!el||el.dataset.bound==='1')return;el.dataset.bound='1';el.querySelectorAll('[data-expr]').forEach(input=>input.addEventListener('input',()=>{const k=input.dataset.expr,v=+input.value,out=el.querySelector(`[data-out="${k}"]`);if(k==='velocity'){expr.velocity=v/127;if(out)out.textContent=String(Math.round(v))}if(k==='sustain'){expr.sustain=v;if(out)out.textContent=`${v.toFixed(2)}s`}if(k==='tone'){expr.tone=v;if(out)out.textContent=`${(v/1000).toFixed(1)}k`}if(k==='space'){expr.space=v/100;if(out)out.textContent=`${Math.round(v)}%`;if(reverbWet&&ctx)reverbWet.gain.setTargetAtTime(expr.space,ctx.currentTime,.02)}}))}
function v4EnsurePlayControls(){const panel=$('#playScreen .instrument-panel');if(!panel)return;if(!$('#playInstrumentSkin')){const skin=document.createElement('div');skin.id='playInstrumentSkin';skin.className='instrument-skin';const tabs=panel.querySelector('.instrument-tabs');tabs.parentNode.insertBefore(skin,tabs)}if(!$('#playExpression')){const d=document.createElement('div');d.innerHTML=v4ExpressionMarkup('play',V4_PLAY_EXPR);const strip=d.firstElementChild;strip.id='playExpression';panel.querySelector('.keyboard-frame').before(strip);v4BindExpression(strip,V4_PLAY_EXPR)}if(!$('#playBassSound')){const selectRow=panel.querySelector('.select-row'),label=document.createElement('label');label.id='playBassSoundWrap';label.innerHTML=`Bass sound<select id="playBassSound">${V4_BASS_PRESETS.map(n=>`<option>${n}</option>`).join('')}</select>`;selectRow.prepend(label);$('#playBassSound').value='Finger Bass';$('#playBassSound').addEventListener('change',v4RefreshPlayInstrument)}}
function v4SetSkin(el,skin,title){if(!el)return;el.style.setProperty('--skin-image',`url('${skin.file}')`);el.style.setProperty('--skin-accent',skin.accent);el.innerHTML=`<div><small>${skin.label}</small><strong>${title}</strong></div><span>PERFORMANCE SKIN</span>`}
function v4RefreshPlayInstrument(){v4EnsurePlayControls();const bass=playInstrument==='bass',bassWrap=$('#playBassSoundWrap'),regular=$('#playSound')?.closest('label');if(bassWrap)bassWrap.style.display=bass?'flex':'none';if(regular)regular.style.display=bass?'none':'flex';let preset=bass?($('#playBassSound')?.value||'Finger Bass'):($('#playSound')?.value||'Studio Grand');if(bass){$('#playInstrumentLabel').textContent=preset;renderKeyboard('#playKeyboard',{octave:Math.max(1,+$('#playOctave').value-1),bass:true,preset})}v4SetSkin($('#playInstrumentSkin'),v4SkinFor(preset,bass?'bass':playInstrument),preset)}
async function v4EnsureWorklet(){await ensureAudio();if(v4WorkletReady)return true;if(!ctx.audioWorklet?.addModule)return false;try{await ctx.audioWorklet.addModule('./recorder-worklet.js');v4WorkletReady=true;return true}catch(e){console.warn('AudioWorklet recorder unavailable',e);return false}}
function v4MakeAudioBuffer(channelBuffers,frames){const count=Math.max(1,channelBuffers.length),b=ctx.createBuffer(count,frames,ctx.sampleRate);channelBuffers.forEach((ab,i)=>b.copyToChannel(new Float32Array(ab),i));return b}
function v4WavBlob(buffer){const ch=buffer.numberOfChannels,sr=buffer.sampleRate,frames=buffer.length,bytes=44+frames*ch*2,ab=new ArrayBuffer(bytes),dv=new DataView(ab);let p=0;const str=s=>{for(let i=0;i<s.length;i++)dv.setUint8(p++,s.charCodeAt(i))},u16=v=>{dv.setUint16(p,v,true);p+=2},u32=v=>{dv.setUint32(p,v,true);p+=4};str('RIFF');u32(bytes-8);str('WAVE');str('fmt ');u32(16);u16(1);u16(ch);u32(sr);u32(sr*ch*2);u16(ch*2);u16(16);str('data');u32(frames*ch*2);const data=Array.from({length:ch},(_,i)=>buffer.getChannelData(i));for(let i=0;i<frames;i++)for(let c=0;c<ch;c++){const s=clamp(data[c][i]||0,-1,1);dv.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
async function v4DecodeSaved(){await ensureAudio();for(const l of session.layers){if(l.blob&&!l.buffer){try{l.buffer=await ctx.decodeAudioData((await l.blob.arrayBuffer()).slice(0));ensureLayerGain(l)}catch(e){console.warn('Could not restore layer',e)}}}}
function v4StopAllSources(){session.layers.forEach(stopLayerSource);sessionPlaying=false}
async function v4PlayAligned(){await v4DecodeSaved();if(sessionPlaying){stopSession();return}const playable=session.layers.filter(l=>l.buffer);if(!playable.length)return;stopScheduler();v4StopAllSources();const when=ctx.currentTime+.09;playable.forEach(l=>startSingleLayer(l,when));setSessionPlayingUI(true)}
function v4StartBacking(when,current){const backing=session.layers.filter(l=>l!==current&&l.buffer);backing.forEach(l=>startSingleLayer(l,when));return backing.length>0}
async function v4CaptureLayer(){const l=sessionLayer();if(recordBusy||!l.source)return;await v4DecodeSaved();if(l.source==='input'&&!micStream){const ok=await setupInput();if(!ok){updateRecordDisplay('INPUT','!','Connect or allow your audio input first');return}}const precise=await v4EnsureWorklet();if(!precise){console.warn('Falling back to MediaRecorder capture');return recordLayerQuantized()}stopSession();stopScheduler();panic();recordBusy=true;renderSession();$('#recordLayerBtn').classList.add('counting');const countStart=ctx.currentTime+.16,recordStart=countStart+barSeconds(session.countIn,session.bpm),duration=barSeconds(session.bars,session.bpm),frames=Math.round(duration*ctx.sampleRate),source=getLayerBus(l);if(session.countIn)countInVisual(countStart,session.countIn);else updateRecordDisplay('ARMED','1','Recording starts on the grid');const node=new AudioWorkletNode(ctx,'loop-capture',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2],channelCount:2,channelCountMode:'explicit'});v4CaptureNode=node;if(!v4SilentGain){v4SilentGain=ctx.createGain();v4SilentGain.gain.value=0;v4SilentGain.connect(ctx.destination)}source.connect(node);node.connect(v4SilentGain);const completed=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Capture timed out')),Math.ceil((recordStart-ctx.currentTime+duration+4)*1000));node.port.onmessage=e=>{if(e.data?.type==='complete'){clearTimeout(timer);resolve(e.data)}}});node.port.postMessage({type:'arm',startFrame:Math.round(recordStart*ctx.sampleRate),frames,channels:2});const delay=Math.max(0,(recordStart-ctx.currentTime)*1000);setTimeout(()=>{if(!recordBusy)return;v4StartBacking(recordStart,l);$('#recordLayerBtn').classList.remove('counting');$('#recordLayerBtn').classList.add('recording');updateRecordDisplay('RECORDING','1.1','Sample-accurate capture • auto-stops on the bar line');if(l.source==='beats')scheduleBeatWindow(l.pattern,recordStart,session.bars,session.bpm);for(let i=0;i<session.bars*4;i++)setTimeout(()=>{if(recordBusy)$('#recordCount').textContent=`${Math.floor(i/4)+1}.${i%4+1}`},Math.max(0,(recordStart-ctx.currentTime)*1000)+i*60000/session.bpm)},delay);try{const data=await completed;l.buffer=v4MakeAudioBuffer(data.channels,data.frames);l.blob=v4WavBlob(l.buffer);l.recordedBpm=session.bpm;l.recordedBars=session.bars;ensureLayerGain(l);updateRecordDisplay('CAPTURED','✓',`${session.bars} bars phase-locked to the session`)}catch(e){console.warn(e);updateRecordDisplay('ERROR','!','Could not capture this layer')}try{source.disconnect(node);node.disconnect()}catch{}v4CaptureNode=null;recordBusy=false;$('#recordLayerBtn').classList.remove('recording','counting');renderSession();if(l.buffer){sessionPlaying=false;await v4PlayAligned()}}
function v4ReplaceButton(id,handler){const old=$(id);if(!old)return null;const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener('click',handler);return fresh}
function v4InstallTransport(){v4ReplaceButton('#recordLayerBtn',v4CaptureLayer);v4ReplaceButton('#redoLayerBtn',()=>{if(recordBusy)return;clearCurrentLayer();v4CaptureLayer()});v4ReplaceButton('#playSessionBtn',v4PlayAligned)}
function v4EnhanceRecordTools(){const l=currentScreen==='record'&&session.layers.length?sessionLayer():null;if(!l||!['keys','chords','bass'].includes(l.source))return;const host=$('#layerSourceTools .tool-box');if(!host)return;const row=host.querySelector('.tool-row');if(l.source==='bass'&&row&&!$('#recordBassSound')){l.sound=V4_BASS_PRESETS.includes(l.sound)?l.sound:'Finger Bass';const label=document.createElement('label');label.innerHTML=`Bass sound<select id="recordBassSound">${V4_BASS_PRESETS.map(n=>`<option ${n===l.sound?'selected':''}>${n}</option>`).join('')}</select>`;row.prepend(label);$('#recordBassSound').addEventListener('change',e=>{l.sound=e.target.value;renderKeyboard('#recordKeyboard',{octave:Math.max(1,l.octave-1),bass:true,mini:true,preset:l.sound});v4UpdateRecordSkin()});renderKeyboard('#recordKeyboard',{octave:Math.max(1,l.octave-1),bass:true,mini:true,preset:l.sound})}if(!host.querySelector('.record-instrument-skin')){const skin=document.createElement('div');skin.className='instrument-skin record-instrument-skin';host.prepend(skin)}if(!host.querySelector('.expression-strip')){const d=document.createElement('div');d.innerHTML=v4ExpressionMarkup('record',v4LayerExpr(l));const strip=d.firstElementChild;host.appendChild(strip);v4BindExpression(strip,v4LayerExpr(l))}v4UpdateRecordSkin()}
function v4UpdateRecordSkin(){const l=session.layers.length?sessionLayer():null;if(!l)return;const preset=l.source==='bass'?(l.sound||'Finger Bass'):(l.sound||'Studio Grand');v4SetSkin($('#layerSourceTools .record-instrument-skin'),v4SkinFor(preset,l.source),preset)}
function v4AttachRefreshHooks(){$('#playScreen .instrument-tabs')?.addEventListener('click',()=>setTimeout(v4RefreshPlayInstrument,0));['playSound','playOctave','playKey','playChordFlavor','playVoicing'].forEach(id=>$('#'+id)?.addEventListener('change',()=>setTimeout(v4RefreshPlayInstrument,0)));const observer=new MutationObserver(()=>setTimeout(v4EnhanceRecordTools,0));observer.observe($('#layerSourceTools'),{childList:true,subtree:true});$('#sourceChooser')?.addEventListener('click',()=>setTimeout(v4EnhanceRecordTools,0))}
function v4Boot(){v4EnsurePlayControls();v4RefreshPlayInstrument();v4InstallTransport();v4AttachRefreshHooks();V4_BASS_PRESETS.slice(1).forEach(n=>{if(![...$('#playSound').options].some(o=>o.value===n))$('#playSound').add(new Option(n,n))})}
v4Boot();
